package main

// The `breeze add` feature registry.
//
// Each feature knows three things: which imports its generated code needs,
// what that code looks like, and where it belongs in the middleware order.
// Everything else — writing the block, rebuilding the dispatcher, gofmt — is
// handled by blocks.go, so adding a feature here is a single table entry.

import (
	"flag"
	"fmt"
	"sort"
	"strings"
)

const featuresFileName = "features_generated.go"

// featureMarkerPrefix namespaces feature blocks, keeping them distinct from
// the breeze:route blocks in routes_generated.go.
const featureMarkerPrefix = "breeze:feature"

// callsBlockName is the dispatcher's block: the list of setup calls, rebuilt
// in priority order after every add.
const callsBlockName = "calls"

// Import lines for the framework subpackages generated code reaches for.
// middlewareImport and scalarImport live in generate_resource.go.
const (
	eventsImport        = `"github.com/nelthaarion/breeze/events"`
	workflowImport      = `"github.com/nelthaarion/breeze/workflow"`
	dashboardImport     = `"github.com/nelthaarion/breeze/dashboard"`
	observabilityImport = `"github.com/nelthaarion/breeze/observability"`
	videoImport         = `"github.com/nelthaarion/breeze/video"`
	oauth2Import        = `"github.com/nelthaarion/breeze/middlewares/oauth2"`
	timeImport          = `"time"`
	logImport           = `"log"`
	contextImport       = `"context"`
	runtimeImport       = `"runtime"`
	osImport            = `"os"`
)

// splitList splits a comma-separated flag value, trimming whitespace and
// dropping empties so "en, fr," yields two entries rather than three.
func splitList(s string) []string {
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if p = strings.TrimSpace(p); p != "" {
			out = append(out, p)
		}
	}
	return out
}

const featuresHeader = `// Code generated by ` + "`breeze add`" + `. DO NOT EDIT outside the marker
// blocks below — re-running add for a feature replaces its block, and hand
// edits outside markers will be lost.
//
// Each block is package scope, so a feature can expose the handle your own
// code needs: EventBus, WorkflowEngine, DashboardCollector.

package main
`

// featuresTemplate is the features_generated.go written by ` + "`breeze new`" + `,
// before any feature has been added. The empty calls block must be present
// from the start: it is the anchor every later add rewrites.
func featuresTemplate() string {
	start, end := markersFor(featureMarkerPrefix, callsBlockName)
	return featuresHeader + `
import (
	"github.com/nelthaarion/breeze"
)

// RegisterGeneratedFeatures wires every feature added with ` + "`breeze add`" + `.
//
// Call it after breeze.New and before app.Run. Router.Use rebuilds each
// route's middleware chain on every call, so registering features after your
// routes is supported — the order below is what decides nesting, not the
// order routes were declared.
func RegisterGeneratedFeatures(app *breeze.Breeze, router *breeze.Router) {
	` + start + `
	` + end + `
}
`
}

// featureCtx is what a feature's generator can consult about the project it
// is being added to.
type featureCtx struct {
	ModulePath string
	// HasEvents and HasObservability report whether those blocks are already
	// present, so a feature can share the existing bus and collector instead
	// of standing up a second one.
	HasEvents        bool
	HasObservability bool
	// HasDashboard reports whether a dashboard block is present, so a feature
	// can route its logs through that collector — which is what stamps a log
	// line with the current trace id — instead of dropping them.
	HasDashboard bool
}

// featureOutput is one feature's generated code.
type featureOutput struct {
	// Body is the package-scope Go source for the block: the setup function
	// plus any vars the feature exposes.
	Body string
	// Imports are import lines needed on top of the feature's static set,
	// decided at generation time (e.g. "time" only when a flag selected a
	// duration).
	Imports []string
	// Files are side files written if they do not already exist — locale
	// JSON, the migrations runner, a placeholder view.
	Files map[string]string
	// Dirs are directories to create.
	Dirs []string
	// Notes are printed after a successful add: what to configure, what the
	// generated code deliberately left as a placeholder.
	Notes []string
}

// feature is one entry in the registry.
type feature struct {
	Name    string
	Summary string
	// Priority orders the dispatcher's call list. Lower runs first, which for
	// middleware means further out: recovery at 10 wraps everything, etag at
	// 110 sits closest to the handler. Features that create shared handles
	// (events, observability) sort before their consumers.
	Priority int
	Imports  []string
	// DependsOn names the features this one consults through featureCtx, so its
	// generated code changes depending on whether they are already installed.
	//
	// It is not a requirement — every feature works standalone; the dependency
	// is that adding one of these later leaves this block wired to the fallback.
	// `add` uses it to say so at the moment it happens, and the registry tests
	// use it to keep this list honest against what the generators actually read.
	DependsOn []string
	// Standalone features write side files only — no block, no dispatcher
	// entry. `add migrator` is the one case: it produces a separate binary.
	Standalone bool
	// Build registers the feature's flags and returns the generator that
	// reads them once parsing is done.
	Build func(fs *flag.FlagSet) func(featureCtx) (featureOutput, error)
}

// featureSetupFunc is the setup function name for a feature. It is derived
// from the name alone, never from flags, so the dispatcher's call list can be
// rebuilt knowing only which blocks are present.
func featureSetupFunc(name string) string {
	return "setup" + strings.ToUpper(name[:1]) + name[1:]
}

// features is the registry, keyed by the name used on the command line.
var features = map[string]*feature{}

func register(f *feature) { features[f.Name] = f }

// featureNames returns every registered name in priority order, which is also
// the most useful order for help output: it reads as the request pipeline.
func featureNames() []string {
	names := make([]string, 0, len(features))
	for n := range features {
		names = append(names, n)
	}
	sort.Slice(names, func(i, j int) bool {
		fi, fj := features[names[i]], features[names[j]]
		if fi.Priority != fj.Priority {
			return fi.Priority < fj.Priority
		}
		return names[i] < names[j]
	})
	return names
}

// rebuildFeatureCalls rewrites the dispatcher's call list from the blocks
// actually present in the file, in priority order.
//
// Rebuilding from the file rather than tracking state elsewhere is what keeps
// add idempotent: the call list is a pure function of which blocks exist.
func rebuildFeatureCalls() error {
	installed := listBlocks(featuresFileName, featureMarkerPrefix)

	ordered := make([]string, 0, len(installed))
	for _, name := range installed {
		if name == callsBlockName {
			continue
		}
		ordered = append(ordered, name)
	}

	sort.Slice(ordered, func(i, j int) bool {
		pi, pj := priorityOf(ordered[i]), priorityOf(ordered[j])
		if pi != pj {
			return pi < pj
		}
		return ordered[i] < ordered[j]
	})

	var body strings.Builder
	for _, name := range ordered {
		fmt.Fprintf(&body, "%s(app, router)\n", featureSetupFunc(name))
	}

	return upsertBlock(blockRequest{
		FileName:  featuresFileName,
		Initial:   featuresTemplate(),
		Prefix:    featureMarkerPrefix,
		Name:      callsBlockName,
		Body:      body.String(),
		Placement: placeReplaceOnly,
	})
}

// priorityOf reports a block's ordering weight. A block with no registry
// entry — a feature from a newer CLI, or one the user renamed — sorts last
// rather than being dropped or crashing the rebuild.
func priorityOf(name string) int {
	if f, ok := features[name]; ok {
		return f.Priority
	}
	return 1 << 30
}

func init() {
	registerCoreFeatures()
	registerMiddlewareFeatures()
	registerRouteFeatures()
	registerFleetFeature()
}
