package mcp

// token.go — the one place a secret or an identifier is minted.
//
// Three callers need random strings and they must not each pick a method:
//
//   - a manually started network-mode breeze-mcp, when no token was supplied;
//   - the orchestrator, when it provisions a service and has to hand that
//     service's own instance a token it can then report back once;
//   - the Streamable HTTP transport, for session identifiers.
//
// The first two are secrets and the third is not, which is exactly why they are
// written together: a session identifier that was accidentally generated by a
// weaker path than a bearer token would be a difference nobody noticed, and a
// bearer token generated by the session path would be worse. Both go through
// crypto/rand here, and the only difference is length.
//
// A generation failure is returned rather than swallowed. math/rand as a
// fallback would turn "the kernel has no entropy" into "the control plane has a
// guessable token", which is the one outcome that must not be silent.

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
)

// tokenBytes is the entropy in a control token. 32 bytes is 256 bits, rendered
// as 64 hex characters — long enough that an online guessing attack is not a
// consideration, and still one copy-pasteable word.
const tokenBytes = 32

// sessionIDBytes is the entropy in a session identifier. Shorter than a token
// because it is not a credential: it is unguessable so that a session cannot be
// hijacked by enumeration, but it authorises nothing on its own. Every request
// carrying one is authenticated by the bearer token as well.
const sessionIDBytes = 16

// NewToken returns a fresh bearer token for a network-mode instance.
//
// The result is hex, so it survives every place a token has to travel through
// unescaped: an environment variable, an Authorization header, a JSON string, a
// shell copy-paste. A base64 token would be shorter and would sometimes contain
// characters that need quoting, which is a trade in the wrong direction for a
// value a human moves by hand exactly once.
func NewToken() (string, error) {
	return randomHex(tokenBytes, "token")
}

// newSessionID returns a fresh Streamable HTTP session identifier.
//
// MCP requires it to be globally unique and to consist only of visible ASCII;
// hex satisfies both without a validation step.
func newSessionID() (string, error) {
	return randomHex(sessionIDBytes, "session id")
}

func randomHex(n int, what string) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("mcp: cannot generate a %s: %w", what, err)
	}
	return hex.EncodeToString(buf), nil
}
