package mcp

// tools_plan.go — answering questions about a project without changing it.
//
// The generation tools are the easy half of an agent's job. The hard half is
// everything around them: what would this configuration produce, what is this
// project already, and what does the difference between the two cost. An agent
// with no way to ask those questions has one strategy available — generate and
// find out — and the cost of a wrong guess is a project that has to be
// un-generated by hand.
//
// So the three tools here read. plan_project runs the real scaffold in a
// throwaway directory and reports the tree it produced; explain_project reads a
// project's own generated blocks back into the configuration that would produce
// them; diff_config puts the two side by side and adds the one fact neither
// contains on its own, which is which of those edits would be refused because
// somebody has since changed the block by hand.
//
// None of them write to the project. plan_project is the one worth being
// explicit about: it does write files, to a temporary directory that is deleted
// before the call returns, and the project's path is never passed to a generator
// at all.

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/nelthaarion/breeze/v2/internal/generator"
)

func registerPlanningTools(s *Server) {
	s.addTool(planProjectTool())
	s.addTool(explainProjectTool())
	s.addTool(diffConfigTool())
}

// ─── shared configuration input ──────────────────────────────────────────────

// configInput is the configuration argument the planning tools take.
//
// Two spellings are accepted because two kinds of caller exist. A model that has
// read describe_schema builds an object, and making it serialise that object
// into YAML first would be a pointless round trip. A caller quoting a
// breeze.yaml it already has should not have to translate it. Both land in the
// same place.
type configInput struct {
	Config     map[string]any `json:"config"`
	ConfigYAML string         `json:"config_yaml"`
}

// resolve turns the argument into a ProjectConfig.
//
// It starts from Defaults and decodes on top, which is the same layering Load
// performs for a config file — so a partial configuration means the same thing
// here as it does on the command line, and a field the caller omitted gets the
// value a generated project would actually have.
//
// KnownFields(true) is set for the same reason Load sets it: a key that is
// silently ignored is the worst outcome available. A model that invents
// `websocket.port` should be told, not quietly handed a project without one.
func (c configInput) resolve() (generator.ProjectConfig, error) {
	cfg := generator.Defaults()

	source := c.ConfigYAML
	if len(c.Config) > 0 {
		if source != "" {
			return cfg, fmt.Errorf("pass either config or config_yaml, not both")
		}
		// Marshalled through YAML rather than decoded from the map directly, so
		// that both spellings go through one decoder and cannot disagree about
		// what a field means.
		encoded, err := yaml.Marshal(c.Config)
		if err != nil {
			return cfg, fmt.Errorf("config: %w", err)
		}
		source = string(encoded)
	}
	if strings.TrimSpace(source) == "" {
		return cfg, nil
	}

	dec := yaml.NewDecoder(strings.NewReader(source))
	dec.KnownFields(true)
	if err := dec.Decode(&cfg); err != nil {
		return cfg, fmt.Errorf("reading the configuration: %w", err)
	}
	return cfg, nil
}

// configToMap renders a configuration as the YAML keys name it.
//
// ProjectConfig carries yaml tags and no json tags, so marshalling it straight
// to JSON would emit Go field names — "WebSocket", "SampleRate" — and those are
// not what describe_schema documents or what a config file uses. Round-tripping
// through YAML means the names in a result are the names a caller can set.
func configToMap(cfg generator.ProjectConfig) (map[string]any, error) {
	encoded, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	out := map[string]any{}
	if err := yaml.Unmarshal(encoded, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// ─── plan_project ────────────────────────────────────────────────────────────

type planProjectArgs struct {
	configInput
	// Name is the project directory the plan is drawn for. It affects the plan
	// only through the generators that use it (the module path, when no module
	// is configured), and the reported paths are relative to the project root
	// regardless of what it is.
	Name     string `json:"name"`
	Template string `json:"template"`
}

func planProjectTool() *tool {
	return &tool{
		name: "breeze_plan_project",
		description: "Preview what a project configuration would generate: the validation " +
			"result, the features it enables, and every file it would create. " +
			"Writes nothing — the scaffold runs in a temporary directory that is " +
			"deleted before the reply. Call this before breeze_new to check a " +
			"configuration is valid and produces what was intended.",
		schema: objectSchema(map[string]any{
			"config": map[string]any{
				"type":        "object",
				"description": "The project configuration, in the shape breeze_describe_schema documents.",
			},
			"config_yaml": stringProp("The project configuration as breeze.yaml text. Use this or config, not both."),
			"name":        stringProp("Project directory name the plan is drawn for. Defaults to app."),
			"template":    map[string]any{"type": "string", "enum": []string{"api", "views"}, "description": "api for a JSON service, views for server-rendered HTML. Defaults to api."},
		}),
		run: func(raw json.RawMessage) toolCallResult {
			var a planProjectArgs
			if err := decodeArgs(raw, &a); err != nil {
				return errorResult("arguments: " + err.Error())
			}
			return planProject(a)
		},
	}
}

// planFile is one file a plan would produce.
type planFile struct {
	Path  string `json:"path"`
	Bytes int64  `json:"bytes,omitempty"`
	// Change is created or modified. A scaffold into an empty directory only
	// creates, but the field is kept so a plan reads the same as the change
	// list a change set reports.
	Change string `json:"change"`
}

// planResult is what plan_project answers.
type planResult struct {
	Valid bool `json:"valid"`
	// Errors is the validation failures, as Validate words them. A single
	// combined message would be shorter and much harder to act on one at a
	// time.
	Errors []string `json:"errors,omitempty"`

	Module   string `json:"module,omitempty"`
	Template string `json:"template"`

	// Features are the features the configuration enables, in the order they
	// would be applied.
	Features []string `json:"features"`

	Files []planFile `json:"files,omitempty"`
	// FileCount is stated separately because a caller that only wants to know
	// whether the plan is large should not have to count an array.
	FileCount int `json:"file_count"`

	// Unsupported are configured settings that validate and then reach no
	// generator. They are not errors and they are not silent either, which is
	// the entire point of reporting them.
	Unsupported []string `json:"unsupported,omitempty"`

	// WroteToDisk is always false. It is in the payload because "this tool does
	// not write" is a promise, and a promise a caller can read is worth more
	// than one in a description.
	WroteToDisk bool `json:"wrote_to_disk"`

	// Warnings carry anything that went wrong in the preview without
	// invalidating it — most often `go mod tidy` failing, which a sandbox runs
	// with the network switched off on purpose.
	Warnings []string `json:"warnings,omitempty"`
}

func planProject(a planProjectArgs) toolCallResult {
	cfg, err := a.resolve()
	if err != nil {
		return structuredErrorResult("the configuration could not be read",
			planResult{Errors: []string{err.Error()}})
	}

	template := a.Template
	if template == "" {
		template = "api"
	}
	name := a.Name
	if name == "" {
		name = "app"
	}

	result := planResult{
		Template:    template,
		Module:      cfg.Module,
		Features:    generator.ConfigFeatureNames(cfg),
		Unsupported: generator.UnsupportedConfigKeys(cfg),
	}

	// Validation first, and on its own. A configuration that does not validate
	// has no plan — running the scaffold anyway would produce a partial tree
	// and invite a caller to read it as the answer.
	if err := cfg.Validate(); err != nil {
		result.Errors = splitValidationError(err)
		return structuredErrorResult("the configuration is not valid, so nothing was planned", result)
	}
	result.Valid = true

	files, warnings, err := scaffoldPlan(cfg, name, template)
	if err != nil {
		result.Errors = []string{err.Error()}
		return structuredErrorResult("the plan could not be produced", result)
	}
	result.Files = files
	result.FileCount = len(files)
	result.Warnings = warnings

	return structuredResult(fmt.Sprintf("%s would create %d file(s) and wire %d feature(s); nothing was written",
		template, len(files), len(result.Features)), result)
}

// scaffoldPlan runs the real scaffold in a temporary directory and reports the
// tree it produced.
//
// The configuration is handed over as a file outside the watched tree rather
// than written into it, so the plan lists what the generators produced and not
// the input it was given.
func scaffoldPlan(cfg generator.ProjectConfig, name, template string) ([]planFile, []string, error) {
	configPath, cleanup, err := writeTempConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	defer cleanup()

	box, err := newEmptySandbox()
	if err != nil {
		return nil, nil, err
	}
	defer box.remove()

	root := box.projectDir()
	argv := []string{name, "--template=" + template, "--config=" + configPath}

	run, err := runInSandbox(root, root, func() error { return generator.New(argv) })
	if err != nil {
		return nil, nil, err
	}
	if run.Err != nil {
		return nil, nil, run.Err
	}

	prefix := name + "/"
	files := make([]planFile, 0, len(run.Changes))
	for _, change := range run.Changes {
		files = append(files, planFile{
			Path:   strings.TrimPrefix(change.Path, prefix),
			Bytes:  change.Bytes,
			Change: change.Change,
		})
	}
	return files, planWarnings(run.Output), nil
}

// writeTempConfig writes a configuration where a generator can read it, outside
// any directory a plan watches.
func writeTempConfig(cfg generator.ProjectConfig) (path string, cleanup func(), err error) {
	encoded, err := yaml.Marshal(cfg)
	if err != nil {
		return "", func() {}, err
	}

	f, err := os.CreateTemp("", "breeze-plan-*.yaml")
	if err != nil {
		return "", func() {}, err
	}
	name := f.Name()
	cleanup = func() { _ = os.Remove(name) }

	if _, err := f.Write(encoded); err != nil {
		f.Close()
		cleanup()
		return "", func() {}, err
	}
	if err := f.Close(); err != nil {
		cleanup()
		return "", func() {}, err
	}
	return name, cleanup, nil
}

// planWarnings picks the lines of a scaffold's output that a caller should see.
//
// The scaffold prints what it created, which the file list already says better.
// What it does not otherwise report is a step that failed without failing the
// command, and `go mod tidy` is that step: a sandbox runs with GOPROXY off, so
// it always fails there and never means anything about the configuration.
func planWarnings(output string) []string {
	var out []string
	for _, line := range strings.Split(output, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		lower := strings.ToLower(line)
		if strings.Contains(lower, "go mod tidy") || strings.Contains(lower, "warning") {
			out = append(out, line)
		}
	}
	return out
}

// splitValidationError recovers the individual problems from Validate's message.
//
// Validate joins them into one error for the command line, where one string is
// what gets printed. A structured result can carry them apart, and a caller
// fixing three problems one at a time should not have to parse a paragraph to
// find the second.
func splitValidationError(err error) []string {
	if err == nil {
		return nil
	}
	message := err.Error()

	// The multi-problem form is "N configuration problems:\n  - first\n  - ...".
	if idx := strings.Index(message, "\n  - "); idx >= 0 {
		var out []string
		for _, part := range strings.Split(message[idx:], "\n  - ") {
			if part = strings.TrimSpace(part); part != "" {
				out = append(out, part)
			}
		}
		return out
	}
	return []string{message}
}

// ─── explain_project ─────────────────────────────────────────────────────────

type explainProjectArgs struct {
	Path string `json:"path"`
}

func explainProjectTool() *tool {
	return &tool{
		name: "breeze_explain_project",
		description: "Read an existing Breeze project back into the configuration that " +
			"describes it: its module, the features wired in, the values they were " +
			"generated with, and its routes. Also reports which generated blocks " +
			"have been edited by hand, because those cannot be regenerated without " +
			"--force. Call this before changing a project you did not just create.",
		schema: objectSchema(map[string]any{
			"path": stringProp("Project root. Defaults to the server's working directory."),
		}),
		run: func(raw json.RawMessage) toolCallResult {
			var a explainProjectArgs
			if err := decodeArgs(raw, &a); err != nil {
				return errorResult("arguments: " + err.Error())
			}
			return explainProject(a.Path)
		},
	}
}

// featureState is one installed feature and whether it is still as generated.
type featureState struct {
	Name string `json:"name"`
	File string `json:"file"`
	// Pristine reports that the block still matches the checksum in its start
	// marker. A block that does not is one somebody edited, and regenerating it
	// would discard that edit.
	Pristine bool `json:"pristine"`
	// Stamp is the recorded checksum, or "" for a block written without one.
	Stamp string `json:"stamp,omitempty"`
}

// projectFacts is what explain_project answers.
type projectFacts struct {
	Path   string `json:"path"`
	Module string `json:"module,omitempty"`

	// Generated reports whether this is a generated project at all — that is,
	// whether the features file exists. A directory that is not one is a
	// likelier explanation for an empty answer than a project with nothing in
	// it, and the two should not look alike.
	Generated bool `json:"generated"`

	Features []featureState         `json:"features"`
	Routes   []generator.RouteEntry `json:"routes"`

	// Models is read from the project's models directory rather than from the
	// reconstructed configuration. A model is a whole generated file, not a
	// marker block, so nothing in the blocks records that one was ever asked
	// for — a configuration rebuilt from them has no models at all, however many
	// the project contains.
	Models []sourceModel `json:"models"`

	// Config is the configuration reconstructed from the blocks, keyed as a
	// breeze.yaml is. It can be fed back to breeze_plan_project or
	// breeze_diff_config.
	Config map[string]any `json:"config"`

	// Edited is the subset of Features that is no longer pristine, extracted so
	// a caller does not have to filter the list to find the one fact that
	// changes what it may do.
	Edited []string `json:"edited,omitempty"`

	// Notes record what could not be recovered. A reconstruction that quietly
	// reports a default for a value it never found would be worse than one that
	// says so.
	Notes []string `json:"notes,omitempty"`
}

func explainProject(path string) toolCallResult {
	facts, _, err := gatherProjectFacts(path)
	if err != nil {
		return errorResult(err.Error())
	}

	summary := fmt.Sprintf("%d feature(s), %d route(s), %d model(s)",
		len(facts.Features), len(facts.Routes), len(facts.Models))
	if len(facts.Edited) > 0 {
		summary += fmt.Sprintf("; %d block(s) edited by hand: %s",
			len(facts.Edited), strings.Join(facts.Edited, ", "))
	}
	return structuredResult(summary, facts)
}

// gatherProjectFacts reads a project and reports what it is.
//
// It is split out of explainProject because breeze_suggest_next_steps reasons
// over exactly these facts, and a second reader would be a second answer to
// "what is in this project" — the two would disagree the first time a feature
// block gained a field, and the advice would then be about a project that does
// not exist.
//
// The reconstructed configuration is returned in its typed form as well as the
// map inside projectFacts. The map is what a caller sets, so it is the right
// thing to report; a rule asking "is WebSocket enabled" wants the field, because
// a map lookup would silently answer "no" if the key were ever renamed.
// # The path is confined here
//
// This is the read path three tools share — explain_project, suggest_next_steps and
// diff_config — and it was the hole the rest of the package's confinement left open.
// It chdirs into the directory it is given and reads go.mod, the features file, the
// route registry and models/, so an unconfined path made it a way to read selected
// contents of any directory on the host and get them back as a structured result.
//
// It is confined in this function rather than in the three callers for the reason
// confine.go gives: three call sites is a list, and a list has to stay complete. The
// resolved path is then used for both halves — the chdir and readSourceModels — so
// they cannot disagree about which directory was approved.
func gatherProjectFacts(path string) (projectFacts, generator.ProjectConfig, error) {
	root, err := orWorkingDir(path)
	if err != nil {
		return projectFacts{}, generator.Defaults(), err
	}
	facts := projectFacts{Path: root}

	cfg := generator.Defaults()
	var notes []string

	err = inProject(root, func() error {
		if module, err := generator.CurrentModulePath(); err == nil {
			facts.Module = module
			cfg.Module = module
		} else {
			notes = append(notes, "no go.mod was readable here, so the module path is unknown: "+err.Error())
		}

		installed := generator.InstalledFeatures()
		facts.Generated = len(installed) > 0 || fileExists(generator.FeaturesFileName)

		for _, name := range installed {
			info, ok := generator.ReadBlock(generator.FeaturesFileName, generator.FeatureMarkerPrefix, name)
			if !ok {
				continue
			}
			facts.Features = append(facts.Features, featureState{
				Name:     name,
				File:     info.File,
				Pristine: info.Pristine,
				Stamp:    info.Stamp,
			})
			if !info.Pristine {
				facts.Edited = append(facts.Edited, name)
			}
			applyFeatureBlockToConfig(&cfg, name, info.Body)
		}

		if routes, err := generator.ParseRoutes(generator.RegistryFileName); err == nil {
			facts.Routes = routes
		} else if facts.Generated {
			notes = append(notes, "the route registry could not be read, so no routes are reported: "+err.Error())
		}
		return nil
	})
	if err != nil {
		return facts, cfg, err
	}

	// Models are read from the source tree, by absolute path, rather than from
	// inside the chdir above. Nothing in a feature block records a model, so
	// this is the only place they can come from.
	models, modelNotes := readSourceModels(facts.Path)
	facts.Models = models
	notes = append(notes, modelNotes...)

	if !facts.Generated {
		notes = append(notes, "this directory has no "+generator.FeaturesFileName+
			", so it is either not a Breeze project or has no features wired in yet")
	}
	// Server host and port live in the scaffold's main.go, which is a template
	// rather than a marker block, so they are not recoverable this way. Saying
	// so is better than reporting the defaults as if they had been read.
	notes = append(notes, "server.host, server.port and server.multicore are written into main.go by the scaffold, not into a feature block, so they are reported as defaults rather than read back")

	facts.Notes = notes
	if facts.Routes == nil {
		facts.Routes = []generator.RouteEntry{}
	}
	if facts.Features == nil {
		facts.Features = []featureState{}
	}
	if facts.Models == nil {
		facts.Models = []sourceModel{}
	}

	configMap, err := configToMap(cfg)
	if err != nil {
		return facts, cfg, fmt.Errorf("the reconstructed configuration could not be rendered: %w", err)
	}
	facts.Config = configMap

	return facts, cfg, nil
}

// inProject runs fn with the working directory set to path.
//
// The generator reads its files relative to the working directory, so this is
// how a read is pointed at a project. It goes through captureStdout because
// that is where the lock lives which makes chdir safe, and because a helper
// that happens to print must not put its output on the protocol stream. What it
// printed is discarded: these are reads, and their answer is the return value.
//
// # The path is confined here as well as in gatherProjectFacts
//
// This is the chdir, so it is the operation that decides which directory the
// generator's relative reads resolve against. gatherProjectFacts resolves the path
// too, because it needs the absolute form for readSourceModels and for the reported
// Path — but diffConfig calls this directly, and a check that lived only in the other
// caller would have left that one reading any directory on the host.
//
// Confining the chdir rather than each caller is the same argument confine.go makes:
// a new reader of a project reaches for this function, and it cannot reach for it
// without the check.
func inProject(path string, fn func() error) error {
	dir, err := resolvePath(path)
	if err != nil {
		return err
	}

	var inner error
	if _, err := captureStdout(func() error {
		return runInDir(dir, func() error {
			inner = fn()
			return nil
		})
	}); err != nil {
		return err
	}
	return inner
}

func fileExists(name string) bool {
	info, err := os.Stat(name)
	return err == nil && !info.IsDir()
}

// ─── reading a feature block back ────────────────────────────────────────────
//
// Every value below was written by a generator through a format string, so it
// can be read back by matching that string's fixed part. Two things make the
// patterns looser than the format strings that produced them.
//
// The first is gofmt. upsertBlock runs format.Source over the whole file, which
// re-aligns the key columns of a struct literal — so the space after a colon
// depends on the longest key in that literal, and matching an exact number of
// spaces would work until a sibling field appeared. Every pattern accepts \s*.
//
// The second is that a block contains prose. The JSON-RPC feature emits an
// example registration inside a comment, and a pattern that matched it would
// report a method the project does not have. stripComments removes whole-line
// comments before anything is matched.

var (
	reFleetEnv     = regexp.MustCompile(`fleetEnv\(\s*"([A-Z_]+)"\s*,\s*"((?:[^"\\]|\\.)*)"\s*\)`)
	reSampleRate   = regexp.MustCompile(`SampleRate:\s*([0-9]+(?:\.[0-9]+)?)`)
	reBackend      = regexp.MustCompile(`Backend:\s*"((?:[^"\\]|\\.)*)"`)
	reWSPath       = regexp.MustCompile(`app\.WebSocket\(\s*"((?:[^"\\]|\\.)*)"`)
	reRPCRun       = regexp.MustCompile(`RPCServer\.Run\(\s*(\d+)\s*,\s*(true|false)\s*\)`)
	reRPCRegister  = regexp.MustCompile(`RPCServer\.(RegisterBlocking|Register)\(\s*"((?:[^"\\]|\\.)*)"`)
	reRPCMaxBytes  = regexp.MustCompile(`RPCServer\.SetMaxMessageBytes\(\s*(\d+)\s*\)`)
	reDocsTitle    = regexp.MustCompile(`Title:\s*"((?:[^"\\]|\\.)*)"`)
	reDocsUIPath   = regexp.MustCompile(`UIPath:\s*"((?:[^"\\]|\\.)*)"`)
	reDocsJSONPath = regexp.MustCompile(`JSONPath:\s*"((?:[^"\\]|\\.)*)"`)
	reAllowOrigins = regexp.MustCompile(`AllowOrigins:\s*"((?:[^"\\]|\\.)*)"`)
	reRequests     = regexp.MustCompile(`Requests:\s*(\d+)`)
	rePer          = regexp.MustCompile(`Per:\s*(\d+)\s*\*\s*time\.Millisecond`)
)

// fleetCtors maps the transport constructor a block calls to the configured
// transport name. The constructor is the honest signal: it is what the project
// will actually run, whatever a config file elsewhere may say.
var fleetCtors = []struct {
	call      string
	transport string
}{
	{"httptransport.New", "http"},
	{"wstransport.New", "ws"},
	{"eventtransport.New", "events"},
}

// applyFeatureBlockToConfig folds one feature's generated block into a config.
func applyFeatureBlockToConfig(cfg *generator.ProjectConfig, name, rawBody string) {
	body := stripComments(rawBody)

	switch name {
	case "fleet":
		cfg.Fleet.Enabled = true
		env := envDefaults(body)
		if v, ok := env["FLEET_SERVICE_NAME"]; ok {
			cfg.Fleet.ServiceName = v
		}
		if v, ok := env["FLEET_WRITE_URL"]; ok {
			cfg.Fleet.AggregatorURL = v
		}
		if v, ok := env["FLEET_WS_URL"]; ok {
			cfg.Fleet.AggregatorWSURL = v
		}
		if m := reSampleRate.FindStringSubmatch(body); m != nil {
			if rate, err := strconv.ParseFloat(m[1], 64); err == nil {
				cfg.Fleet.SampleRate = rate
			}
		}
		for _, ctor := range fleetCtors {
			if strings.Contains(body, ctor.call) {
				cfg.Fleet.Transport = ctor.transport
				break
			}
		}
		if m := reBackend.FindStringSubmatch(body); m != nil {
			cfg.Fleet.Backend = m[1]
		}

	case "websocket":
		cfg.WebSocket.Enabled = true
		if m := reWSPath.FindStringSubmatch(body); m != nil {
			cfg.WebSocket.Path = m[1]
		}

	case "jsonrpc":
		cfg.JSONRPC.Enabled = true
		if m := reRPCRun.FindStringSubmatch(body); m != nil {
			if port, err := strconv.Atoi(m[1]); err == nil {
				cfg.JSONRPC.Port = port
			}
			cfg.JSONRPC.Multicore = m[2] == "true"
		}
		if m := reRPCMaxBytes.FindStringSubmatch(body); m != nil {
			if max, err := strconv.Atoi(m[1]); err == nil {
				cfg.JSONRPC.MaxMessageBytes = max
			}
		}
		for _, m := range reRPCRegister.FindAllStringSubmatch(body, -1) {
			cfg.JSONRPC.Methods = append(cfg.JSONRPC.Methods, m[2])
			if m[1] == "RegisterBlocking" {
				cfg.JSONRPC.BlockingMethods = append(cfg.JSONRPC.BlockingMethods, m[2])
			}
		}

	case "docs":
		cfg.Docs.Enabled = true
		if m := reDocsTitle.FindStringSubmatch(body); m != nil {
			cfg.Docs.Title = m[1]
		}
		if m := reDocsUIPath.FindStringSubmatch(body); m != nil {
			cfg.Docs.UIPath = m[1]
		}
		if m := reDocsJSONPath.FindStringSubmatch(body); m != nil {
			cfg.Docs.SpecPath = m[1]
		}

	case "cors":
		entry := generator.MiddlewareConfig{Name: name}
		if m := reAllowOrigins.FindStringSubmatch(body); m != nil && m[1] != "" {
			entry.Origins = strings.Split(m[1], ",")
		}
		cfg.Middleware = append(cfg.Middleware, entry)

	case "ratelimit":
		entry := generator.MiddlewareConfig{Name: name}
		if m := reRequests.FindStringSubmatch(body); m != nil {
			if requests, err := strconv.Atoi(m[1]); err == nil {
				entry.RPS = perSecond(requests, body)
			}
		}
		cfg.Middleware = append(cfg.Middleware, entry)

	default:
		// Every other feature is wired without a configurable value: its
		// presence is the whole of what it contributes. It is already reported
		// in Features, and inventing a middleware entry for one that is not a
		// middleware would put a key in the config that means nothing.
		if _, isMiddleware := middlewareFeature(name); isMiddleware {
			cfg.Middleware = append(cfg.Middleware, generator.MiddlewareConfig{Name: name})
		}
	}
}

// perSecond converts a generated Requests/Per pair back into a per-second rate.
//
// The generator emits a window in milliseconds, and rps is what the
// configuration expresses; a window that is not a whole number of seconds
// cannot round-trip exactly, so it is scaled rather than reported as if it had
// been configured directly.
func perSecond(requests int, body string) int {
	m := rePer.FindStringSubmatch(body)
	if m == nil {
		return requests
	}
	window, err := strconv.Atoi(m[1])
	if err != nil || window <= 0 {
		return requests
	}
	return int(float64(requests) * 1000 / float64(window))
}

// middlewareFeature reports whether a feature name is one the middleware
// section of a configuration can carry.
//
// It asks the feature registry rather than holding a list: a middleware added to
// the registry later should not need this file edited to be recognised.
func middlewareFeature(name string) (string, bool) {
	canonical, ok := knownFeature(name)
	if !ok {
		return "", false
	}
	summary, _ := generator.FeatureSummary(canonical)
	lower := strings.ToLower(summary)
	return canonical, strings.Contains(lower, "middleware") ||
		strings.Contains(lower, "rate limiting") ||
		strings.Contains(lower, "cors") ||
		strings.Contains(lower, "jwt")
}

// envDefaults collects the fallback values of the fleetEnv calls in a block.
func envDefaults(body string) map[string]string {
	out := map[string]string{}
	for _, m := range reFleetEnv.FindAllStringSubmatch(body, -1) {
		out[m[1]] = m[2]
	}
	return out
}

// stripComments removes whole-line comments from generated source.
//
// Only whole lines. Trimming from the first "//" on any line would cut a URL in
// half, and the generated Fleet block is full of them.
func stripComments(body string) string {
	lines := strings.Split(body, "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "//") {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

// ─── diff_config ─────────────────────────────────────────────────────────────

type diffConfigArgs struct {
	configInput
	// ExistingPath is the project to compare against.
	ExistingPath string `json:"existing_path"`
}

func diffConfigTool() *tool {
	return &tool{
		name: "breeze_diff_config",
		description: "Compare a proposed configuration against an existing project: which " +
			"settings change, which files that would touch, and which of those edits " +
			"would be refused because the block has been modified by hand. Writes " +
			"nothing. Call this before applying a configuration to a project that " +
			"already exists.",
		schema: objectSchema(map[string]any{
			"existing_path": stringProp("Root of the project to compare against. Defaults to the server's working directory."),
			"config": map[string]any{
				"type":        "object",
				"description": "The proposed configuration, in the shape breeze_describe_schema documents.",
			},
			"config_yaml": stringProp("The proposed configuration as breeze.yaml text. Use this or config, not both."),
		}),
		run: func(raw json.RawMessage) toolCallResult {
			var a diffConfigArgs
			if err := decodeArgs(raw, &a); err != nil {
				return errorResult("arguments: " + err.Error())
			}
			return diffConfig(a)
		},
	}
}

// configChange is one setting whose value would change.
type configChange struct {
	// Path is the dotted configuration path, as a --flag spells it.
	Path string `json:"path"`
	From any    `json:"from"`
	To   any    `json:"to"`
}

// blockedTouch is a file the proposal would rewrite and may not.
type blockedTouch struct {
	Feature string `json:"feature"`
	File    string `json:"file"`
	Reason  string `json:"reason"`
}

// diffResult is what diff_config answers.
type diffResult struct {
	ExistingPath string `json:"existing_path"`

	Valid  bool     `json:"valid"`
	Errors []string `json:"errors,omitempty"`

	// Changes are the settings that differ, dotted-path keyed.
	Changes []configChange `json:"changes"`

	// FeaturesAdded and FeaturesKept split the proposal's feature list by
	// whether the project already has them.
	FeaturesAdded []string `json:"features_added,omitempty"`
	FeaturesKept  []string `json:"features_kept,omitempty"`

	// Touches is what applying the proposal actually did to a copy of the
	// project. It is observed rather than predicted: the real feature
	// generators ran, in a sandbox.
	Touches []fileChange `json:"touches"`

	// Blocked are the edits that would be refused, and why. This is the reason
	// the tool exists: a caller that applies a configuration to a project whose
	// blocks have been edited gets a refusal partway through, and finding that
	// out first costs nothing.
	Blocked []blockedTouch `json:"blocked,omitempty"`

	Unsupported []string `json:"unsupported,omitempty"`
	WroteToDisk bool     `json:"wrote_to_disk"`
	Notes       []string `json:"notes,omitempty"`
}

func diffConfig(a diffConfigArgs) toolCallResult {
	proposed, err := a.resolve()
	if err != nil {
		return structuredErrorResult("the proposed configuration could not be read",
			diffResult{Errors: []string{err.Error()}})
	}

	result := diffResult{
		ExistingPath: a.ExistingPath,
		Unsupported:  generator.UnsupportedConfigKeys(proposed),
	}
	if err := proposed.Validate(); err != nil {
		result.Errors = splitValidationError(err)
		return structuredErrorResult("the proposed configuration is not valid, so nothing was compared", result)
	}
	result.Valid = true

	// The current state is read back from the project's own blocks rather than
	// from a breeze.yaml beside it. A config file records what was asked for
	// once; the blocks record what is there now, and those are the same thing
	// only until somebody edits either one.
	current := generator.Defaults()
	installed := map[string]generator.BlockInfo{}

	if err := inProject(a.ExistingPath, func() error {
		if module, err := generator.CurrentModulePath(); err == nil {
			current.Module = module
		}
		for _, name := range generator.InstalledFeatures() {
			info, ok := generator.ReadBlock(generator.FeaturesFileName, generator.FeatureMarkerPrefix, name)
			if !ok {
				continue
			}
			installed[name] = info
			applyFeatureBlockToConfig(&current, name, info.Body)
		}
		return nil
	}); err != nil {
		return errorResult(err.Error())
	}

	// A proposal that leaves module unset is not asking to rename the module.
	// Comparing an empty string against the real one would report a change the
	// caller did not request and no generator would make.
	if proposed.Module == "" {
		proposed.Module = current.Module
	}

	changes, err := compareConfigs(current, proposed)
	if err != nil {
		return errorResult(err.Error())
	}
	result.Changes = changes

	for _, name := range generator.ConfigFeatureNames(proposed) {
		if _, have := installed[name]; have {
			result.FeaturesKept = append(result.FeaturesKept, name)
			continue
		}
		result.FeaturesAdded = append(result.FeaturesAdded, name)
	}

	// Blocked is decided from the checksum stamped into each block, which is
	// the same evidence the generator itself uses when it refuses.
	for _, name := range result.FeaturesKept {
		info := installed[name]
		if info.Pristine {
			continue
		}
		reason := "the block no longer matches the checksum in its start marker, so it has been edited by hand; regenerating it needs force and would discard that edit"
		if info.Stamp == "" {
			reason = "the block carries no checksum, so there is no evidence it is unmodified; regenerating it needs force"
		}
		result.Blocked = append(result.Blocked, blockedTouch{Feature: name, File: info.File, Reason: reason})
	}

	touches, notes, err := applyPlan(a.ExistingPath, proposed, current.Module)
	if err != nil {
		result.Notes = append(result.Notes, "the file-level effect could not be measured: "+err.Error())
	} else {
		result.Touches = touches
		result.Notes = append(result.Notes, notes...)
	}
	if result.Touches == nil {
		result.Touches = []fileChange{}
	}
	if result.Changes == nil {
		result.Changes = []configChange{}
	}

	summary := fmt.Sprintf("%d setting(s) change, %d file(s) would be touched", len(result.Changes), len(result.Touches))
	if len(result.Blocked) > 0 {
		summary += fmt.Sprintf("; %d block(s) would be refused", len(result.Blocked))
	}
	return structuredResult(summary, result)
}

// applyPlan measures what applying a configuration to a project would touch, by
// applying it to a copy.
func applyPlan(projectPath string, cfg generator.ProjectConfig, modulePath string) ([]fileChange, []string, error) {
	root, err := orWorkingDir(projectPath)
	if err != nil {
		return nil, nil, err
	}
	box, err := newSandbox(root)
	if err != nil {
		return nil, nil, err
	}
	defer box.remove()

	dir := box.projectDir()
	var applyErr error

	run, err := runInSandbox(dir, dir, func() error {
		// ApplyConfig chdirs into the directory it is given, and it is already
		// being run from inside it, so "." is the project.
		_, applyErr = generator.ApplyConfig(".", cfg, modulePath)
		return nil
	})
	if err != nil {
		return nil, nil, err
	}

	var notes []string
	if applyErr != nil {
		// A refusal is the answer, not a failure: it is what applying this
		// configuration to this project would do. The files it managed to
		// touch first are reported with it, because that is what a real run
		// would leave behind.
		notes = append(notes, "applying this configuration would fail: "+applyErr.Error())
	}
	return run.Changes, notes, nil
}

// orWorkingDir resolves a path argument to an absolute path inside the workspace.
//
// # It is not "or the working directory" anymore
//
// The name is kept because six call sites use it and the meaning is unchanged for a
// legitimate caller: empty still means the server's working directory. What changed
// is that the answer now goes through resolvePath, so a path outside the configured
// workspace is refused instead of returned.
//
// The signature gained an error for that reason. It previously could not fail, and
// that was the problem — every caller treated a path as a fact about the request
// rather than a claim to check.
func orWorkingDir(path string) (string, error) {
	return resolvePath(path)
}

// ─── comparing two configurations ────────────────────────────────────────────

// compareConfigs reports the settings that differ between two configurations,
// as dotted paths.
//
// Both sides are rendered through YAML first, so the paths are spelled with the
// yaml tags — which are the same strings the --section.field flags use and the
// same ones describe_schema documents. Walking the structs directly would mean
// repeating that tag lookup here, and a third spelling of a field name is a
// third thing that can drift.
func compareConfigs(before, after generator.ProjectConfig) ([]configChange, error) {
	from, err := configToMap(before)
	if err != nil {
		return nil, err
	}
	to, err := configToMap(after)
	if err != nil {
		return nil, err
	}

	var out []configChange
	diffValues("", from, to, &out)
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

func diffValues(path string, before, after any, out *[]configChange) {
	beforeMap, beforeIsMap := before.(map[string]any)
	afterMap, afterIsMap := after.(map[string]any)
	if beforeIsMap && afterIsMap {
		for _, key := range unionKeys(beforeMap, afterMap) {
			diffValues(join(path, key), beforeMap[key], afterMap[key], out)
		}
		return
	}

	beforeList, beforeIsList := before.([]any)
	afterList, afterIsList := after.([]any)
	if beforeIsList && afterIsList {
		diffLists(path, beforeList, afterList, out)
		return
	}

	if !reflect.DeepEqual(before, after) {
		*out = append(*out, configChange{Path: path, From: before, To: after})
	}
}

// diffLists compares the keyed sections.
//
// middleware, models and routes are sequences whose elements are named, and
// their positions carry no meaning: a config that lists cors after ratelimit
// describes the same project. Matching on the element's own name is what makes
// the reported path "middleware.ratelimit.rps" rather than "middleware.1.rps",
// and what stops a reordered file reading as a change to every entry.
func diffLists(path string, before, after []any, out *[]configChange) {
	beforeByName, beforeNamed := indexByName(before)
	afterByName, afterNamed := indexByName(after)

	if !beforeNamed || !afterNamed {
		// A plain list — jsonrpc.methods, middleware.<name>.origins. Its order
		// is part of its value, so it is compared whole.
		if !reflect.DeepEqual(before, after) {
			*out = append(*out, configChange{Path: path, From: before, To: after})
		}
		return
	}

	for _, name := range unionKeys(beforeByName, afterByName) {
		beforeElem, hadBefore := beforeByName[name]
		afterElem, hasAfter := afterByName[name]

		switch {
		case !hadBefore:
			*out = append(*out, configChange{Path: join(path, name), From: nil, To: afterElem})
		case !hasAfter:
			*out = append(*out, configChange{Path: join(path, name), From: beforeElem, To: nil})
		default:
			diffValues(join(path, name), beforeElem, afterElem, out)
		}
	}
}

// elemNameKeys are the fields that identify a keyed element, in the order they
// are tried. They match the generator's own elemNameFields, because a path this
// reports has to be one its flag parser accepts.
var elemNameKeys = []string{"name", "resource"}

// indexByName keys a list of named elements by name, reporting whether every
// element had one.
func indexByName(list []any) (map[string]any, bool) {
	out := make(map[string]any, len(list))
	for _, item := range list {
		asMap, ok := item.(map[string]any)
		if !ok {
			return nil, false
		}
		name := ""
		for _, key := range elemNameKeys {
			if value, ok := asMap[key].(string); ok && value != "" {
				name = value
				break
			}
		}
		if name == "" {
			return nil, false
		}
		out[name] = asMap
	}
	return out, true
}

func unionKeys[V any](a, b map[string]V) []string {
	seen := make(map[string]bool, len(a)+len(b))
	out := make([]string, 0, len(a)+len(b))
	for _, m := range []map[string]V{a, b} {
		for key := range m {
			if seen[key] {
				continue
			}
			seen[key] = true
			out = append(out, key)
		}
	}
	sort.Strings(out)
	return out
}

func join(path, key string) string {
	if path == "" {
		return key
	}
	return path + "." + key
}
