package mcp

// tools_verify_test.go — the tests that prove the verification tools tell a
// working project apart from a broken one.
//
// The fixtures here are real Go modules that the real toolchain really compiles.
// A fixture that fed canned `go build` output to the parsers would test the
// regular expressions and nothing else, and the regular expressions are not the
// part that is likely to be wrong — the part that is likely to be wrong is the
// assumption about what the toolchain prints. So every test below runs `go`.
//
// The modules are deliberately dependency-free rather than generated by
// `breeze new`. A scaffolded project needs the breeze module resolved over the
// network to compile, so on an offline machine `go build` would fail for a reason
// that has nothing to do with the project's own correctness, and a test asserting
// "a good project verifies clean" would fail everywhere except on a warm cache.
// What these tools actually promise is to report the toolchain's findings
// faithfully, and a two-package module exercises that completely.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// goodModule is a module that compiles, vets clean, passes its tests, and has
// one allocation-free benchmark and one that allocates.
//
// The two benchmarks exist so the allocation reporting can be checked in both
// directions: a tool that reported every benchmark as zero-allocation would pass
// a test that only had the first one.
var goodModule = map[string]string{
	"go.mod": "module example.com/verifyme\n\ngo 1.24\n",

	"calc/calc.go": `package calc

// Add returns the sum of two integers.
func Add(a, b int) int { return a + b }

// Join concatenates two strings, which allocates.
func Join(a, b string) string { return a + b }
`,

	"calc/calc_test.go": `package calc

import "testing"

var (
	intSink    int
	stringSink string
)

func TestAdd(t *testing.T) {
	if got := Add(2, 3); got != 5 {
		t.Errorf("Add(2,3) = %d, want 5", got)
	}
}

func BenchmarkAddIsAllocationFree(b *testing.B) {
	for i := 0; i < b.N; i++ {
		intSink = Add(i, 1)
	}
}

func BenchmarkJoinAllocates(b *testing.B) {
	left, right := "left", "right"
	for i := 0; i < b.N; i++ {
		stringSink = Join(left, right)
	}
}
`,

	// A second package with no test file at all, so the coverage tool has an
	// untested package to report. This is the case where a percentage would be
	// misleading rather than merely low.
	"untested/untested.go": `package untested

// Unused is never called by any test.
func Unused() string { return "nothing exercises this" }
`,
}

// newToolchainFixture writes a module and returns its root.
func newToolchainFixture(t *testing.T, files map[string]string) string {
	t.Helper()

	root := t.TempDir()
	for name, content := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("creating %s: %v", filepath.Dir(name), err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("writing %s: %v", name, err)
		}
	}
	return root
}

// withFile returns a copy of a file set with one entry replaced or added. This
// keeps each broken variant a one-line difference from the working one, so a test
// failure points at the change rather than at a whole separate fixture.
func withFile(base map[string]string, name, content string) map[string]string {
	out := make(map[string]string, len(base)+1)
	for k, v := range base {
		out[k] = v
	}
	out[name] = content
	return out
}

// structOf pulls the structured payload out of a tool result.
//
// The result has been through the JSON-RPC encoder by the time a test sees it, so
// the payload is a map rather than the report struct. Reading it as a map is
// deliberate: it checks the JSON field names an agent will actually receive,
// which asserting against the Go struct would not.
func structOf(t *testing.T, result toolCallResult) map[string]any {
	t.Helper()

	shape, ok := result.StructuredContent.(map[string]any)
	if !ok {
		t.Fatalf("structured content is %T, not an object: %#v",
			result.StructuredContent, result.StructuredContent)
	}
	return shape
}

// stepsByName indexes a verification report's steps.
func stepsByName(t *testing.T, report map[string]any) map[string]map[string]any {
	t.Helper()

	raw, ok := report["steps"].([]any)
	if !ok {
		t.Fatalf("steps is %T, not a list", report["steps"])
	}

	out := make(map[string]map[string]any, len(raw))
	for _, entry := range raw {
		step, ok := entry.(map[string]any)
		if !ok {
			t.Fatalf("a step is %T, not an object", entry)
		}
		name, _ := step["name"].(string)
		out[name] = step
	}
	return out
}

// listOf reads a list-valued field as objects.
func listOf(t *testing.T, node map[string]any, key string) []map[string]any {
	t.Helper()

	raw, ok := node[key].([]any)
	if !ok {
		return nil
	}
	out := make([]map[string]any, 0, len(raw))
	for _, entry := range raw {
		obj, ok := entry.(map[string]any)
		if !ok {
			t.Fatalf("%s contains a %T, not an object", key, entry)
		}
		out = append(out, obj)
	}
	return out
}

// notesOf reads a notes list as one searchable string.
func notesOf(node map[string]any) string {
	raw, ok := node["notes"].([]any)
	if !ok {
		return ""
	}
	parts := make([]string, 0, len(raw))
	for _, entry := range raw {
		if text, ok := entry.(string); ok {
			parts = append(parts, text)
		}
	}
	return strings.Join(parts, " | ")
}

// ─── verify_project ──────────────────────────────────────────────────────────

// TestVerifyProjectPassesAWorkingModule is the control. Without it, a tool that
// reported everything as broken would pass every other test in this file.
func TestVerifyProjectPassesAWorkingModule(t *testing.T) {
	root := newToolchainFixture(t, goodModule)

	result := callTool(t, NewServer("test"), "breeze_verify_project", map[string]any{
		"path": root,
	})
	if result.IsError {
		t.Fatalf("verifying a working module reported a tool error: %s", result.Content[0].Text)
	}

	report := structOf(t, result)
	if ok, _ := report["ok"].(bool); !ok {
		t.Fatalf("a working module did not verify: %s\n%s",
			result.Content[0].Text, renderStructured("", report))
	}
	if failure, _ := report["first_failure"].(string); failure != "" {
		t.Errorf("first_failure = %q on a clean run, want empty", failure)
	}

	// Every stage must actually have run. A tool that silently skipped vet would
	// otherwise look identical to one that ran it.
	steps := stepsByName(t, report)
	for _, name := range []string{"build", "vet", "test", "idioms"} {
		step, present := steps[name]
		if !present {
			t.Errorf("the report has no %s step", name)
			continue
		}
		if status, _ := step["status"].(string); status != "passed" {
			t.Errorf(
				"%s step status = %q, want passed (summary: %v)",
				name,
				status,
				step["summary"],
			)
		}
	}

	// The build and vet steps must name the command they ran, so a caller can
	// reproduce the result by hand.
	if command, _ := steps["build"]["command"].(string); !strings.Contains(command, "go build") {
		t.Errorf("build step command = %q", command)
	}
}

// TestVerifyProjectReportsABrokenBuildWithFileAndLine is the reason these tools
// return records instead of output.
//
// A caller that has just been told "the build failed" has to open the whole tree
// to find out where. The assertion here is that the file and the line come back
// as fields, and that the line is the one the error is actually on.
func TestVerifyProjectReportsABrokenBuildWithFileAndLine(t *testing.T) {
	// The type error is on line 5 of the file, counted from the package clause.
	broken := withFile(goodModule, "calc/calc.go", `package calc

func Add(a, b int) int { return a + b }

var Broken int = "this is a string, not an int"
`)
	root := newToolchainFixture(t, broken)

	result := callTool(t, NewServer("test"), "breeze_verify_project", map[string]any{
		"path": root,
	})
	report := structOf(t, result)

	if ok, _ := report["ok"].(bool); ok {
		t.Fatalf("a module that does not compile was reported as verified:\n%s",
			renderStructured("", report))
	}
	if failure, _ := report["first_failure"].(string); failure != "build" {
		t.Errorf("first_failure = %q, want build", failure)
	}

	steps := stepsByName(t, report)
	diagnostics := listOf(t, steps["build"], "diagnostics")
	if len(diagnostics) == 0 {
		t.Fatalf("the build failed but reported no located diagnostics; unparsed output was %v",
			steps["build"]["unparsed_output"])
	}

	found := false
	for _, d := range diagnostics {
		file, _ := d["file"].(string)
		line, _ := d["line"].(float64)
		message, _ := d["message"].(string)

		if strings.HasSuffix(file, "calc.go") && int(line) == 5 {
			found = true
			if message == "" {
				t.Error("a diagnostic has a file and line but no message")
			}
		}
	}
	if !found {
		t.Errorf("no diagnostic pointed at calc.go line 5; got %v", diagnostics)
	}

	// The counted tally must agree with the list. These are read by different
	// callers — one branches on the number, the other displays the records — and
	// a disagreement between them would make one of the two wrong.
	counts, _ := report["counts"].(map[string]any)
	if errors, _ := counts["build_errors"].(float64); int(errors) != len(diagnostics) {
		t.Errorf(
			"counts.build_errors = %v but %d diagnostics were listed",
			errors,
			len(diagnostics),
		)
	}
}

// TestVerifyProjectSkipsTestsWhenTheBuildIsBrokenAndSaysWhy pins a judgement
// call rather than a mechanism.
//
// `go test` on a package that does not compile reports the compile error again.
// Running it anyway would give a caller three reports of one problem and imply
// the tests are also wrong, so the step is skipped — and the skip has to say it
// was a consequence, or it reads as "the tests were not checked" with no reason.
func TestVerifyProjectSkipsTestsWhenTheBuildIsBrokenAndSaysWhy(t *testing.T) {
	broken := withFile(goodModule, "calc/calc.go", "package calc\n\nthis is not Go at all\n")
	root := newToolchainFixture(t, broken)

	result := callTool(t, NewServer("test"), "breeze_verify_project", map[string]any{
		"path": root,
	})
	steps := stepsByName(t, structOf(t, result))

	status, _ := steps["test"]["status"].(string)
	if status != "skipped" {
		t.Errorf("test step status = %q, want skipped when the build is broken", status)
	}
	summary, _ := steps["test"]["summary"].(string)
	if !strings.Contains(summary, "does not compile") {
		t.Errorf("the skip does not explain itself: %q", summary)
	}
}

// TestVerifyProjectReportsAFailingTestWithItsAssertionOutput checks the part of
// a test failure that is actually useful.
//
// The name of a failing test says which behaviour broke; the indented lines
// beneath it say what was expected and what happened. Only the second is enough
// to act on, so it must survive the trip through the parser.
func TestVerifyProjectReportsAFailingTestWithItsAssertionOutput(t *testing.T) {
	failing := withFile(goodModule, "calc/calc_test.go", `package calc

import "testing"

func TestAddIsDeliberatelyWrong(t *testing.T) {
	t.Errorf("Add(2,3) = %d, want 99", Add(2, 3))
}
`)
	root := newToolchainFixture(t, failing)

	result := callTool(t, NewServer("test"), "breeze_verify_project", map[string]any{
		"path": root,
	})
	report := structOf(t, result)

	if ok, _ := report["ok"].(bool); ok {
		t.Fatal("a module with a failing test was reported as verified")
	}
	if failure, _ := report["first_failure"].(string); failure != "test" {
		t.Errorf("first_failure = %q, want test — the build and vet are fine here", failure)
	}

	steps := stepsByName(t, report)
	failures := listOf(t, steps["test"], "failures")
	if len(failures) == 0 {
		t.Fatalf("no failing test was reported; summary was %v", steps["test"]["summary"])
	}

	first := failures[0]
	if name, _ := first["name"].(string); name != "TestAddIsDeliberatelyWrong" {
		t.Errorf("failure name = %q", name)
	}
	if pkg, _ := first["package"].(string); !strings.Contains(pkg, "calc") {
		t.Errorf("failure package = %q, want the calc package", pkg)
	}

	detail := strings.Join(func() []string {
		raw, _ := first["detail"].([]any)
		out := make([]string, 0, len(raw))
		for _, entry := range raw {
			if text, ok := entry.(string); ok {
				out = append(out, text)
			}
		}
		return out
	}(), " ")

	if !strings.Contains(detail, "want 99") {
		t.Errorf("the assertion output was lost; detail = %q", detail)
	}
}

// TestVerifyProjectSkipTestsSaysWhatItDidNotCheck.
//
// A green result that quietly skipped the tests is the most dangerous output
// this tool could produce, because it looks exactly like a full pass.
func TestVerifyProjectSkipTestsSaysWhatItDidNotCheck(t *testing.T) {
	root := newToolchainFixture(t, goodModule)

	result := callTool(t, NewServer("test"), "breeze_verify_project", map[string]any{
		"path":       root,
		"skip_tests": true,
	})
	report := structOf(t, result)

	if ok, _ := report["ok"].(bool); !ok {
		t.Fatalf(
			"a working module failed a build-and-vet-only check:\n%s",
			renderStructured("", report),
		)
	}
	if skipped, _ := report["tests_skipped"].(bool); !skipped {
		t.Error("tests_skipped is false after skip_tests was set")
	}
	if notes := notesOf(report); !strings.Contains(notes, "tests were not run") {
		t.Errorf("a green skip-tests result does not disclose what it did not check: %q", notes)
	}
}

// TestVerifyToolsRejectADirectoryThatIsNotAModule.
//
// Without this check the toolchain reports "go.mod file not found" once per
// stage, which reads as four problems and buries the real one: the path is wrong.
func TestVerifyToolsRejectADirectoryThatIsNotAModule(t *testing.T) {
	root := t.TempDir()
	srv := NewServer("test")

	for _, name := range []string{
		"breeze_verify_project", "breeze_run_benchmarks", "breeze_get_test_coverage",
	} {
		result := callTool(t, srv, name, map[string]any{"path": root})
		if !result.IsError {
			t.Errorf("%s accepted a directory with no go.mod", name)
			continue
		}
		if !strings.Contains(result.Content[0].Text, "go.mod") {
			t.Errorf("%s did not explain the problem: %s", name, result.Content[0].Text)
		}
	}
}

// ─── run_benchmarks ──────────────────────────────────────────────────────────

// TestRunBenchmarksReturnsNumbersNotText is the whole point of the tool.
//
// "1234 ns/op" as a string cannot be compared with another measurement without
// parsing it a second time, so an agent asked whether a change made things
// slower would have to reimplement this parser to answer.
func TestRunBenchmarksReturnsNumbersNotText(t *testing.T) {
	root := newToolchainFixture(t, goodModule)

	result := callTool(t, NewServer("test"), "breeze_run_benchmarks", map[string]any{
		"path": root,
		// A fixed, tiny iteration count: the numbers are being checked for
		// presence and shape, not for stability, and a default 1s per benchmark
		// would make this test slow for no gain.
		"benchtime": "10x",
	})
	if result.IsError {
		t.Fatalf("running benchmarks failed: %s", result.Content[0].Text)
	}

	report := structOf(t, result)
	benchmarks := listOf(t, report, "benchmarks")
	if len(benchmarks) < 2 {
		t.Fatalf("expected both fixture benchmarks, got %d: %s",
			len(benchmarks), renderStructured("", report))
	}

	byName := map[string]map[string]any{}
	for _, b := range benchmarks {
		name, _ := b["name"].(string)
		byName[name] = b
	}

	free, ok := byName["BenchmarkAddIsAllocationFree"]
	if !ok {
		t.Fatalf("the allocation-free benchmark is missing; got %v", byName)
	}
	if ns, present := free["ns_per_op"].(float64); !present || ns <= 0 {
		t.Errorf("ns_per_op = %v, want a positive number", free["ns_per_op"])
	}
	if iterations, _ := free["iterations"].(float64); iterations <= 0 {
		t.Errorf("iterations = %v, want a positive count", free["iterations"])
	}
	if allocs, present := free["allocs_per_op"].(float64); !present || allocs != 0 {
		t.Errorf(
			"allocs_per_op = %v for an allocation-free benchmark, want 0",
			free["allocs_per_op"],
		)
	}

	// And the other direction: a benchmark that allocates must not be reported
	// as allocation-free, or the zero-allocation list means nothing.
	allocating, ok := byName["BenchmarkJoinAllocates"]
	if !ok {
		t.Fatalf("the allocating benchmark is missing; got %v", byName)
	}
	if allocs, _ := allocating["allocs_per_op"].(float64); allocs <= 0 {
		t.Errorf("allocs_per_op = %v for a benchmark that concatenates strings, want > 0", allocs)
	}

	zero := map[string]bool{}
	raw, _ := report["zero_allocation"].([]any)
	for _, entry := range raw {
		if name, ok := entry.(string); ok {
			zero[name] = true
		}
	}
	if !zero["BenchmarkAddIsAllocationFree"] {
		t.Error("the allocation-free benchmark is not in zero_allocation")
	}
	if zero["BenchmarkJoinAllocates"] {
		t.Error("an allocating benchmark was listed as zero-allocation")
	}
}

// TestRunBenchmarksOnAPatternThatMatchesNothingSaysSo.
//
// An empty list is ambiguous — no benchmarks, or no match — and the two need
// different responses, so the tool has to name which it was.
func TestRunBenchmarksOnAPatternThatMatchesNothingSaysSo(t *testing.T) {
	root := newToolchainFixture(t, goodModule)

	result := callTool(t, NewServer("test"), "breeze_run_benchmarks", map[string]any{
		"path":      root,
		"filter":    "BenchmarkNothingIsNamedThis",
		"benchtime": "10x",
	})
	if result.IsError {
		t.Fatalf(
			"an empty benchmark run was reported as a tool failure: %s",
			result.Content[0].Text,
		)
	}

	report := structOf(t, result)
	if count, _ := report["count"].(float64); count != 0 {
		t.Errorf("count = %v, want 0", count)
	}
	if notes := notesOf(report); !strings.Contains(notes, "did not match") &&
		!strings.Contains(notes, "no benchmark matched") {
		t.Errorf("an empty result did not explain itself: %q", notes)
	}
}

// ─── get_test_coverage ───────────────────────────────────────────────────────

// TestCoverageReportsPerPackageAndNamesUntestedOnesSeparately.
//
// A package with no tests has no meaningful percentage. Counting it as zero
// would drag the average down and imply its statements were checked and missed,
// which is a different and less fixable problem than "nobody wrote a test yet".
func TestCoverageReportsPerPackageAndNamesUntestedOnesSeparately(t *testing.T) {
	root := newToolchainFixture(t, goodModule)

	result := callTool(t, NewServer("test"), "breeze_get_test_coverage", map[string]any{
		"path": root,
	})
	if result.IsError {
		t.Fatalf("measuring coverage failed: %s", result.Content[0].Text)
	}

	report := structOf(t, result)
	if passed, _ := report["tests_passed"].(bool); !passed {
		t.Errorf(
			"the fixture's tests pass, but tests_passed is false:\n%s",
			renderStructured("", report),
		)
	}

	total, present := report["total_percent"].(float64)
	if !present {
		t.Fatalf("no total_percent was reported:\n%s", renderStructured("", report))
	}
	if total <= 0 || total > 100 {
		t.Errorf("total_percent = %v, want a percentage", total)
	}

	// The tested package must carry a number, and the untested one must not be
	// silently folded into the average as a zero.
	var measured, untestedListed bool
	for _, pkg := range listOf(t, report, "packages") {
		name, _ := pkg["package"].(string)
		switch {
		case strings.HasSuffix(name, "/calc"):
			if _, ok := pkg["coverage_percent"].(float64); !ok {
				t.Errorf("the calc package has no coverage_percent: %v", pkg)
			}
			measured = true
		case strings.HasSuffix(name, "/untested"):
			if _, ok := pkg["coverage_percent"].(float64); ok {
				t.Errorf("a package with no test files was given a percentage: %v", pkg)
			}
		}
	}
	if !measured {
		t.Error("the tested package is absent from the report")
	}

	raw, _ := report["untested_packages"].([]any)
	for _, entry := range raw {
		if name, ok := entry.(string); ok && strings.HasSuffix(name, "/untested") {
			untestedListed = true
		}
	}
	if !untestedListed {
		t.Errorf("the package with no tests is not in untested_packages: %v", raw)
	}

	// The averaging method has to be stated. A caller comparing this figure with
	// a statement-weighted one from another tool would otherwise conclude the
	// project changed when only the arithmetic did.
	if notes := notesOf(report); !strings.Contains(notes, "mean") {
		t.Errorf("the report does not say how total_percent was computed: %q", notes)
	}
}

// TestCoverageStillReportsWhenTheSuiteFails, and says the suite failed.
//
// Coverage measured during a failing run is real but was taken while the project
// was broken, and a caller acting on the number needs to know that.
func TestCoverageStillReportsWhenTheSuiteFails(t *testing.T) {
	failing := withFile(goodModule, "calc/calc_test.go", `package calc

import "testing"

func TestAddFails(t *testing.T) {
	if Add(2, 3) == 5 {
		t.Errorf("this test fails on purpose")
	}
}
`)
	root := newToolchainFixture(t, failing)

	result := callTool(t, NewServer("test"), "breeze_get_test_coverage", map[string]any{
		"path": root,
	})
	if result.IsError {
		t.Fatalf(
			"coverage on a failing suite was reported as a tool error: %s",
			result.Content[0].Text,
		)
	}

	report := structOf(t, result)
	if passed, _ := report["tests_passed"].(bool); passed {
		t.Error("tests_passed is true although the suite failed")
	}
	if notes := notesOf(report); !strings.Contains(notes, "failed") {
		t.Errorf("the report does not disclose that the suite failed: %q", notes)
	}
	if failures := listOf(t, report, "failures"); len(failures) == 0 {
		t.Error("no failing test was named")
	}
}
