package dashboard

// assets.go — which client bundle the dashboard links.
//
// Both bundles are committed and embedded (see gen_assets.go at the repo root):
// dashboard.css/dashboard.js are the readable sources, dashboard.min.css and
// dashboard.min.js are the esbuild output regenerated by `go generate ./...`.
//
// The minified pair is the default because the dashboard is a real page load for
// a real person: 49KB of CSS and 117KB of JS against 40KB and 71KB is ~55KB of
// comments and indentation per visit, paid by whoever opened the dashboard rather
// than by the developer who wrote it.
//
// DevMode selects the readable pair, matching what breeze.TemplateConfig.DevMode
// already does for the SPA runtime (see breezeRuntime in template.go). The two
// switches are deliberately the same idea under the same name: stepping through
// minified output in devtools is not debugging, and a developer who has asked for
// dev mode once should not have to ask again per asset.
//
// Both files are served either way — router.ServeStatic exposes the whole public
// directory — so this decides what the layout *links*, not what exists. That
// matters for a sourcemap-less debugging session: a developer can always open
// /dashboard/assets/dashboard.js by hand.

const (
	styleMinified = "dashboard.min.css"
	styleReadable = "dashboard.css"

	scriptMinified = "dashboard.min.js"
	scriptReadable = "dashboard.js"
)

// assetNames reports the stylesheet and script filenames the layout should link.
//
// Filenames rather than a boolean passed into the template, so the decision is
// made once in Go and the template contains no logic: a template that branches on
// a flag is a second place for the default to be wrong.
func assetNames(devMode bool) (style, script string) {
	if devMode {
		return styleReadable, scriptReadable
	}
	return styleMinified, scriptMinified
}
