package generator

import (
	"flag"
	"fmt"
	"path/filepath"
	"strings"
	"time"
)

// generateWorkflow writes a workflow definition plus one step stub per step.
//
// The definition is returned by a function rather than assigned to a package
// var: a var would build the definition during package initialisation, before
// the engine exists, and there would be no way to sequence that against the
// rest of startup.
func generateWorkflow(modulePath, name string, args []string) error {
	fs := flag.NewFlagSet("generate workflow", flag.ContinueOnError)
	steps := fs.String("steps", "", "comma-separated step names (e.g. --steps=validate,charge,ship)")
	retry := fs.Bool("retry", false, "attach an exponential-backoff retry policy to every step")
	compensate := fs.Bool("compensate", false, "attach a compensation (rollback) function to every step")
	timeout := fs.String("timeout", "30s", "per-step timeout (e.g. --timeout=5s)")
	force := fs.Bool("force", false, "overwrite an existing workflow file")

	flagArgs, positional := splitFlagsAndPositional(fs, args)
	if err := parseFlags(fs, flagArgs); err != nil {
		return err
	}

	// Steps may be given either way: --steps=a,b,c or as trailing positionals.
	// Both read naturally and there is no reason to reject one.
	raw := splitList(*steps)
	raw = append(raw, positional...)
	if len(raw) == 0 {
		return fmt.Errorf("usage: breeze generate workflow %s --steps=validate,charge,ship", name)
	}

	type step struct {
		Label string // as typed, used as the workflow step name
		Ident string // Go identifier fragment
	}
	stepList := make([]step, 0, len(raw))
	seen := make(map[string]bool, len(raw))
	for _, s := range raw {
		if err := requireIdent("step name", s); err != nil {
			return err
		}
		ident := identFrom(s)
		// A duplicate step name makes Definition.Validate fail at runtime, long
		// after generation. Catching it here means the error names the input.
		if seen[strings.ToLower(ident)] {
			return fmt.Errorf("duplicate step %q", s)
		}
		seen[strings.ToLower(ident)] = true
		stepList = append(stepList, step{Label: s, Ident: ident})
	}

	timeoutExpr, err := parseDurationFlag("--timeout", *timeout)
	if err != nil {
		return err
	}

	lower := lowerFirst(name)

	var b strings.Builder
	b.WriteString("// Code generated by `breeze generate workflow` â€” edit freely.\n")
	b.WriteString("package workflows\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"log\"\n")
	b.WriteString("\t\"time\"\n\n")
	b.WriteString("\t\"github.com/nelthaarion/breeze/workflow\"\n")
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "// %sName is the identifier the workflow is registered and started under.\n", name)
	fmt.Fprintf(&b, "const %sName = %q\n\n", name, toSlug(name))

	fmt.Fprintf(&b, "// %s builds the %s workflow definition.\n//\n", name, name)
	b.WriteString("// Steps run in the order declared. A step that returns an error stops the\n")
	if *compensate {
		b.WriteString("// execution and runs the compensation of every step that already\n")
		b.WriteString("// succeeded, in reverse order.\n")
	} else {
		b.WriteString("// execution; add workflow.WithCompensation to roll back completed steps.\n")
	}
	fmt.Fprintf(&b, "func %s() *workflow.Definition {\n", name)
	fmt.Fprintf(&b, "\treturn workflow.New(%sName).\n", name)

	for i, s := range stepList {
		fmt.Fprintf(&b, "\t\tStep(%q, %s%s,\n", s.Label, lower, s.Ident)
		// WithTimeout is always emitted, which is also what keeps the `time`
		// import used regardless of the other flags.
		fmt.Fprintf(&b, "\t\t\tworkflow.WithTimeout(%s),\n", timeoutExpr)
		if *retry {
			b.WriteString("\t\t\tworkflow.WithRetry(workflow.RetryPolicy{\n")
			b.WriteString("\t\t\t\tMaxAttempts:  3,\n")
			b.WriteString("\t\t\t\tBackoff:      workflow.BackoffExponential,\n")
			b.WriteString("\t\t\t\tInitialDelay: 100 * time.Millisecond,\n")
			// Jitter is on by default because retries without it reproduce the
			// load spike that caused the failure.
			b.WriteString("\t\t\t\tJitter:       0.2,\n")
			b.WriteString("\t\t\t}),\n")
		}
		if *compensate {
			fmt.Fprintf(&b, "\t\t\tworkflow.WithCompensation(%s%sUndo),\n", lower, s.Ident)
		}
		if i == len(stepList)-1 {
			b.WriteString("\t\t)\n")
		} else {
			b.WriteString("\t\t).\n")
		}
	}
	b.WriteString("}\n\n")

	for _, s := range stepList {
		fmt.Fprintf(&b, "// %s%s is the %q step.\n", lower, s.Ident, s.Label)
		fmt.Fprintf(&b, "func %s%s(ctx *workflow.Context) error {\n", lower, s.Ident)
		fmt.Fprintf(&b, "\tlog.Printf(%q)\n", name+": "+s.Label)
		b.WriteString("\t// TODO: implement\n")
		b.WriteString("\treturn nil\n}\n\n")

		if *compensate {
			fmt.Fprintf(&b, "// %s%sUndo rolls back %s%s. It runs only if that step succeeded and a\n", lower, s.Ident, lower, s.Ident)
			b.WriteString("// later step failed, so it must be idempotent.\n")
			fmt.Fprintf(&b, "func %s%sUndo(ctx *workflow.Context) error {\n", lower, s.Ident)
			fmt.Fprintf(&b, "\tlog.Printf(%q)\n", name+": undo "+s.Label)
			b.WriteString("\t// TODO: implement\n")
			b.WriteString("\treturn nil\n}\n\n")
		}
	}

	path := filepath.Join("workflows", fileSlug(name)+".go")
	if err := writeGeneratedGoFile(path, b.String(), *force); err != nil {
		return err
	}

	notes := []string{
		fmt.Sprintf("Register it:  WorkflowEngine.Register(workflows.%s())", name),
		fmt.Sprintf("Run it:       res, err := WorkflowEngine.Run(ctx, workflows.%sName, payload)", name),
		fmt.Sprintf("Import as:    \"%s/workflows\"", modulePath),
	}
	if !hasBlock(featuresFileName, featureMarkerPrefix, "workflow") {
		notes = append(notes, "Run `breeze add workflow` â€” the WorkflowEngine this needs is declared by that block.")
	}
	printNotes(notes)
	return nil
}

// parseDurationFlag validates a duration flag and returns it as a Go
// expression.
//
// Returning the expression rather than the input is the whole point: the raw
// flag value is `30s`, which is a valid time.ParseDuration input and not valid
// Go source. Pasting it into a generated const produced
// `const XInterval = 30s`, which fails in format.Source with a parse error
// naming a line the user never wrote.
func parseDurationFlag(flagName, value string) (string, error) {
	if value == "" {
		return "", fmt.Errorf("%s cannot be empty", flagName)
	}
	d, err := time.ParseDuration(value)
	if err != nil {
		return "", fmt.Errorf("invalid %s %q â€” expected a Go duration such as 30s, 5m, or 1h", flagName, value)
	}
	if d <= 0 {
		return "", fmt.Errorf("invalid %s %q â€” must be positive", flagName, value)
	}
	return goDurationExpr(d), nil
}

// goDurationExpr renders a duration as readable Go source: 90s becomes
// "90 * time.Second" rather than "time.Duration(90000000000)". It picks the
// largest unit that divides evenly, so the generated code reads the way the
// flag was typed.
func goDurationExpr(d time.Duration) string {
	for _, u := range []struct {
		size time.Duration
		name string
	}{
		{time.Hour, "time.Hour"},
		{time.Minute, "time.Minute"},
		{time.Second, "time.Second"},
		{time.Millisecond, "time.Millisecond"},
		{time.Microsecond, "time.Microsecond"},
	} {
		if d%u.size == 0 {
			n := d / u.size
			if n == 1 {
				return u.name
			}
			return fmt.Sprintf("%d * %s", n, u.name)
		}
	}
	return fmt.Sprintf("%d * time.Nanosecond", int64(d))
}
