package generator

import (
	"fmt"
	"strings"
)

// tempStructs is set by generateGRPCFiles before calling the adapter
// generators. It maps struct type names to their field info, so the
// adapter generators can emit field-by-field conversion code.
var tempStructs map[string]*grpcStruct

// findStruct looks up a struct by name from tempStructs.
func findStruct(name string) (*grpcStruct, bool) {
	if tempStructs == nil {
		return nil, false
	}
	s, ok := tempStructs[name]
	return s, ok
}

// generate_grpc_adapters.go â€” Phase 5 (server adapter) + Phase 6 (client wrapper).
//
// The server adapter imports the user's handlers package and converts between
// the generated protobuf message types (used for gRPC wire serialization) and
// the user's Go struct types (used by the business logic).
//
// The user's handlers package path is: <modulePath>/handlers

// â”€â”€â”€ Phase 5: Server Adapter â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

func generateServerAdapter(modulePath string, iface *grpcInterface) (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by breeze generate grpc. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", iface.Name)

	handlersImport := modulePath + "/handlers"
	fmt.Fprintf(&b, `import (
        "context"

        "google.golang.org/grpc/codes"
        "google.golang.org/grpc/status"

        handlers %q
)

`, handlersImport)

	// Adapter struct â€” holds the user's implementation.
	fmt.Fprintf(
		&b,
		"// %sGRPCServer adapts a user-provided handlers.%s implementation\n",
		iface.Name,
		iface.Name,
	)
	fmt.Fprintf(&b, "// to the generated gRPC %sServer interface.\n", iface.Name)
	fmt.Fprintf(&b, "type %sGRPCServer struct {\n", iface.Name)
	fmt.Fprintf(&b, "\timpl handlers.%s\n", iface.Name)
	b.WriteString("}\n\n")

	// Constructor.
	fmt.Fprintf(
		&b,
		"// New%sGRPCServer wraps the given handlers.%s implementation.\n",
		iface.Name,
		iface.Name,
	)
	fmt.Fprintf(
		&b,
		"func New%sGRPCServer(impl handlers.%s) *%sGRPCServer {\n",
		iface.Name,
		iface.Name,
		iface.Name,
	)
	fmt.Fprintf(&b, "\treturn &%sGRPCServer{impl: impl}\n", iface.Name)
	b.WriteString("}\n\n")

	// Method forwarders.
	for _, m := range iface.Methods {
		emitServerMethodForwarder(&b, iface.Name, m)
	}

	return b.String(), nil
}

func emitServerMethodForwarder(b *strings.Builder, serviceName string, m grpcMethod) {
	rpcName := m.Name
	recvType := fmt.Sprintf("%sGRPCServer", serviceName)

	switch m.Kind {
	case grpcUnary:
		// gRPC server method: Method(ctx, *PbReq) (*PbResp, error)
		// User method:        Method_GRPC(ctx, handlers.Req) (*handlers.Resp, error)
		fmt.Fprintf(b, "func (s *%s) %s(ctx context.Context, req *%s) (*%s, error) {\n",
			recvType, rpcName, m.ReqType, m.RespType)
		// Convert pb request â†’ handlers request (field-by-field copy).
		fmt.Fprintf(b, "\tuserReq := handlers.%s{\n", m.ReqType)
		if s, ok := findStruct(m.ReqType); ok {
			for _, f := range s.Fields {
				fmt.Fprintf(b, "\t\t%s: req.Get%s(),\n", f.GoName, f.GoName)
			}
		}
		b.WriteString("\t}\n")
		// Call user implementation.
		fmt.Fprintf(b, "\tresp, err := s.impl.%s(ctx, userReq)\n", m.Name)
		b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		// Convert handlers response â†’ pb response.
		fmt.Fprintf(b, "\treturn &%s{\n", m.RespType)
		if s, ok := findStruct(m.RespType); ok {
			for _, f := range s.Fields {
				fmt.Fprintf(b, "\t\t%s: resp.%s,\n", f.GoName, f.GoName)
			}
		}
		b.WriteString("\t}, nil\n")
		b.WriteString("}\n\n")

	case grpcServerStream:
		fmt.Fprintf(b, "func (s *%s) %s(req *%s, stream %s) error {\n",
			recvType, rpcName, m.ReqType, m.StreamType)
		b.WriteString("\t// ServerSideStreaming adapter â€” streaming not yet fully supported.\n")
		b.WriteString(
			"\t// The unary path works; streaming requires stream interface generation.\n",
		)
		fmt.Fprintf(
			b,
			"\treturn status.Errorf(codes.Unimplemented, \"%s streaming not yet supported\")\n",
			rpcName,
		)
		b.WriteString("}\n\n")

	case grpcClientStream:
		fmt.Fprintf(b, "func (s *%s) %s(stream %s) (*%s, error) {\n",
			recvType, rpcName, m.StreamType, m.RespType)
		b.WriteString("\t// ClientSideStreaming adapter â€” streaming not yet fully supported.\n")
		fmt.Fprintf(
			b,
			"\treturn nil, status.Errorf(codes.Unimplemented, \"%s streaming not yet supported\")\n",
			rpcName,
		)
		b.WriteString("}\n\n")

	case grpcBidiStream:
		fmt.Fprintf(b, "func (s *%s) %s(stream %s) error {\n",
			recvType, rpcName, m.StreamType)
		b.WriteString("\t// Bidirectional adapter â€” streaming not yet fully supported.\n")
		fmt.Fprintf(
			b,
			"\treturn status.Errorf(codes.Unimplemented, \"%s streaming not yet supported\")\n",
			rpcName,
		)
		b.WriteString("}\n\n")
	}
}

// â”€â”€â”€ Phase 6: Client Wrapper â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

func generateClientWrapper(modulePath string, iface *grpcInterface) (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by breeze generate grpc. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", iface.Name)

	handlersImport := modulePath + "/handlers"
	fmt.Fprintf(&b, `import (
        "context"

        "google.golang.org/grpc"

        handlers %q
)

`, handlersImport)

	// Client struct.
	fmt.Fprintf(
		&b,
		"// %sGRPCClient wraps the generated gRPC client and exposes typed\n",
		iface.Name,
	)
	b.WriteString("// methods matching the original _GRPC signatures (minus the _GRPC suffix).\n")
	fmt.Fprintf(&b, "type %sGRPCClient struct {\n", iface.Name)
	fmt.Fprintf(&b, "\tclient %sClient\n", iface.Name)
	b.WriteString("}\n\n")

	// Constructor.
	fmt.Fprintf(
		&b,
		"// New%sGRPCClient creates a typed client using the given gRPC connection.\n",
		iface.Name,
	)
	fmt.Fprintf(
		&b,
		"func New%sGRPCClient(cc grpc.ClientConnInterface) *%sGRPCClient {\n",
		iface.Name,
		iface.Name,
	)
	fmt.Fprintf(&b, "\treturn &%sGRPCClient{client: New%sClient(cc)}\n", iface.Name, iface.Name)
	b.WriteString("}\n\n")

	// Typed client methods.
	for _, m := range iface.Methods {
		emitClientMethodWrapper(&b, iface.Name, m)
	}

	return b.String(), nil
}

func emitClientMethodWrapper(b *strings.Builder, serviceName string, m grpcMethod) {
	rpcName := m.Name
	recvType := fmt.Sprintf("%sGRPCClient", serviceName)

	switch m.Kind {
	case grpcUnary:
		// Typed client method: Method(ctx, handlers.Req) (*handlers.Resp, error)
		fmt.Fprintf(
			b,
			"func (c *%s) %s(ctx context.Context, req handlers.%s) (*handlers.%s, error) {\n",
			recvType,
			rpcName,
			m.ReqType,
			m.RespType,
		)
		// Convert handlers request â†’ pb request.
		fmt.Fprintf(b, "\tpbReq := &%s{\n", m.ReqType)
		if s, ok := findStruct(m.ReqType); ok {
			for _, f := range s.Fields {
				fmt.Fprintf(b, "\t\t%s: req.%s,\n", f.GoName, f.GoName)
			}
		}
		b.WriteString("\t}\n")
		// Call the gRPC client.
		fmt.Fprintf(b, "\tpbResp, err := c.client.%s(ctx, pbReq)\n", rpcName)
		b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		// Convert pb response â†’ handlers response.
		fmt.Fprintf(b, "\treturn &handlers.%s{\n", m.RespType)
		if s, ok := findStruct(m.RespType); ok {
			for _, f := range s.Fields {
				fmt.Fprintf(b, "\t\t%s: pbResp.Get%s(),\n", f.GoName, f.GoName)
			}
		}
		b.WriteString("\t}, nil\n")
		b.WriteString("}\n\n")

	case grpcServerStream:
		fmt.Fprintf(b, "func (c *%s) %s(ctx context.Context, req handlers.%s) (%s, error) {\n",
			recvType, rpcName, m.ReqType, m.StreamType)
		fmt.Fprintf(b, "\tpbReq := &%s{\n", m.ReqType)
		if s, ok := findStruct(m.ReqType); ok {
			for _, f := range s.Fields {
				fmt.Fprintf(b, "\t\t%s: req.%s,\n", f.GoName, f.GoName)
			}
		}
		b.WriteString("\t}\n")
		fmt.Fprintf(b, "\treturn c.client.%s(ctx, pbReq)\n", rpcName)
		b.WriteString("}\n\n")

	case grpcClientStream, grpcBidiStream:
		fmt.Fprintf(b, "func (c *%s) %s(ctx context.Context) (%s, error) {\n",
			recvType, rpcName, m.StreamType)
		fmt.Fprintf(b, "\treturn c.client.%s(ctx)\n", rpcName)
		b.WriteString("}\n\n")
	}
}
