package generator

import (
	"flag"
	"fmt"
	"path/filepath"
	"strings"
)

// generateWS writes a WebSocket handler plus its registration block.
//
// The wiring goes into features_generated.go rather than routes_generated.go
// because app.WebSocket is a method on *breeze.Breeze, and only the features
// dispatcher receives that â€” RegisterGeneratedRoutes is handed the router
// alone. The block name is prefixed (`wsChat`) so it can never collide with a
// feature registered by `breeze add`.
func generateWS(modulePath, name string, args []string) error {
	fs := flag.NewFlagSet("generate ws", flag.ContinueOnError)
	pathOverride := fs.String("path", "", "WebSocket path (default /ws/<name>)")
	force := fs.Bool("force", false, "overwrite an existing handler file")

	flagArgs, _ := splitFlagsAndPositional(fs, args)
	if err := parseFlags(fs, flagArgs); err != nil {
		return err
	}

	wsPath, err := resolveRoutePath(*pathOverride, "ws/"+strings.ToLower(name))
	if err != nil {
		return err
	}

	lower := lowerFirst(name)

	var b strings.Builder
	b.WriteString("// Code generated by `breeze generate ws` â€” edit freely.\n")
	b.WriteString("package ws\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"log\"\n\n")
	b.WriteString("\t\"github.com/nelthaarion/breeze\"\n")
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "// %s handles connections on %s.\n//\n", name, wsPath)
	b.WriteString("// The hub is injected rather than created here so the handler can broadcast\n")
	b.WriteString("// to every connected peer. It is set by New, which is called after\n")
	b.WriteString("// app.WebSocket returns the hub for this path.\n")
	fmt.Fprintf(&b, "type %s struct {\n", name)
	b.WriteString("\thub *breeze.WSHub\n")
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "// New%s returns a handler ready to be passed to app.WebSocket.\n", name)
	fmt.Fprintf(&b, "func New%s() *%s {\n\treturn &%s{}\n}\n\n", name, name, name)

	fmt.Fprintf(&b, "// SetHub records the hub app.WebSocket returned, enabling broadcasts.\n")
	fmt.Fprintf(&b, "func (h *%s) SetHub(hub *breeze.WSHub) {\n\th.hub = hub\n}\n\n", name)

	// OnConnect
	b.WriteString("// OnConnect runs once after the handshake completes.\n")
	fmt.Fprintf(&b, "func (h *%s) OnConnect(conn *breeze.WSConn) {\n", name)
	fmt.Fprintf(&b, "\tlog.Printf(%q, h.count())\n", name+": client connected (%d online)")
	b.WriteString("\t// TODO: implement\n")
	b.WriteString("}\n\n")

	// OnMessage
	b.WriteString("// OnMessage runs for each complete message, after defragmentation.\n")
	b.WriteString("// opcode is breeze.WsOpText or breeze.WsOpBinary.\n")
	fmt.Fprintf(&b, "func (h *%s) OnMessage(conn *breeze.WSConn, opcode byte, payload []byte) {\n", name)
	b.WriteString("\tif opcode != breeze.WsOpText {\n")
	b.WriteString("\t\t// Binary frame â€” handle or ignore.\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\t// Echo back to the sender. Replace with real routing.\n")
	b.WriteString("\tif err := conn.Send(opcode, payload); err != nil {\n")
	fmt.Fprintf(&b, "\t\tlog.Printf(%q, err)\n", name+": send failed: %v")
	b.WriteString("\t}\n\n")
	b.WriteString("\t// To reach every other client instead:\n")
	b.WriteString("\t//\th.hub.BroadcastExcept(opcode, payload, conn)\n")
	b.WriteString("}\n\n")

	// OnClose
	b.WriteString("// OnClose runs when the connection closes, with the close code and reason.\n")
	fmt.Fprintf(&b, "func (h *%s) OnClose(conn *breeze.WSConn, code uint16, reason string) {\n", name)
	fmt.Fprintf(&b, "\tlog.Printf(%q, code, reason)\n", name+": client disconnected (%d %s)")
	b.WriteString("\t// TODO: implement\n")
	b.WriteString("}\n\n")

	// count guards the nil hub: SetHub is called after app.WebSocket returns,
	// so a connection arriving before that would otherwise panic.
	b.WriteString("// count reports the number of live connections, or -1 before the hub is set.\n")
	fmt.Fprintf(&b, "func (h *%s) count() int64 {\n", name)
	b.WriteString("\tif h.hub == nil {\n\t\treturn -1\n\t}\n")
	b.WriteString("\treturn h.hub.Count()\n}\n")

	path := filepath.Join("ws", fileSlug(name)+".go")
	if err := writeGeneratedGoFile(path, b.String(), *force); err != nil {
		return err
	}

	// The features block: mount the handler and hand it back its hub.
	var body strings.Builder
	fmt.Fprintf(&body, "// %sHandler serves %s.\n", name, wsPath)
	fmt.Fprintf(&body, "var %sHandler = ws.New%s()\n\n", lower, name)
	fmt.Fprintf(&body, "func %s(app *breeze.Breeze, router *breeze.Router) {\n", featureSetupFunc("ws"+name))
	fmt.Fprintf(&body, "\thub := app.WebSocket(%q, %sHandler)\n", wsPath, lower)
	fmt.Fprintf(&body, "\t%sHandler.SetHub(hub)\n", lower)
	body.WriteString("}\n")

	if err := upsertGeneratedFeature("ws"+name, body.String(), []string{
		`"github.com/nelthaarion/breeze"`,
		fmt.Sprintf("%q", modulePath+"/ws"),
	}); err != nil {
		return err
	}

	printNotes([]string{
		fmt.Sprintf("Serving on:   %s", wsPath),
		fmt.Sprintf("Broadcast:    ws.%sHandler is reachable from main as %sHandler", name, lower),
		"Test it:      websocat " + "ws://localhost:8080" + wsPath,
	})
	return nil
}
