package generator

import (
	"flag"
	"fmt"
	"path/filepath"
	"strings"
)

// generateMiddleware writes a breeze.HandlerFunc middleware stub.
//
// Deliberately not auto-wired. Two reasons, both real:
//
//   - Ordering is the decision that makes a middleware correct or broken, and
//     only the user knows where theirs belongs. Appending it blindly to the end
//     of the chain would put it inside auth and rate limiting, which is wrong
//     for most of what people write.
//   - A local package named `middleware` collides with the framework's
//     `middleware "github.com/nelthaarion/breeze/middlewares"` alias in any
//     generated file that imports both â€” and features_generated.go imports the
//     framework one for nine of its features.
//
// So this prints the exact router.Use line instead of writing it.
func generateMiddleware(modulePath, name string, args []string) error {
	fs := flag.NewFlagSet("generate middleware", flag.ContinueOnError)
	force := fs.Bool("force", false, "overwrite an existing middleware file")

	flagArgs, _ := splitFlagsAndPositional(fs, args)
	if err := parseFlags(fs, flagArgs); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by `breeze generate middleware` â€” edit freely.\n")
	b.WriteString("package middleware\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/nelthaarion/breeze\"\n")
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "// %s returns a middleware that ... (describe the behaviour).\n//\n", name)
	b.WriteString("// The chain only advances when ctx.Next() is called, so returning without\n")
	b.WriteString("// calling it short-circuits the request â€” that is how a middleware rejects\n")
	b.WriteString("// one. Set the status and write the body first. ctx.Abort() does the same\n")
	b.WriteString("// thing explicitly and also stops any outer middleware from continuing.\n")
	fmt.Fprintf(&b, "func %s() breeze.HandlerFunc {\n", name)
	b.WriteString("\treturn func(ctx *breeze.Context) {\n")
	b.WriteString("\t\t// Runs before the handler. To reject the request:\n")
	b.WriteString("\t\t//\n")
	b.WriteString("\t\t//\tctx.Status(401)\n")
	b.WriteString("\t\t//\tctx.JSON(...)\n")
	b.WriteString("\t\t//\tctx.Abort()\n")
	b.WriteString("\t\t//\treturn\n\n")
	b.WriteString("\t\tctx.Next()\n\n")
	b.WriteString("\t\t// Runs after the handler. The response body may already be\n")
	b.WriteString("\t\t// written by this point, so headers set here can be too late.\n")
	b.WriteString("\t}\n}\n")

	path := filepath.Join("middleware", fileSlug(name)+".go")
	if err := writeGeneratedGoFile(path, b.String(), *force); err != nil {
		return err
	}

	printNotes([]string{
		"Not wired automatically â€” middleware order decides behaviour, so it is yours to place.",
		fmt.Sprintf("In main.go, add:  router.Use(middleware.%s())", name),
		fmt.Sprintf("Import as:        middleware \"%s/middleware\"", modulePath),
		"Earlier Use() calls run further outside; place auth after rate limiting, recovery first.",
	})
	return nil
}
