package generator

// ownership.go — which feature owns a generated file.
//
// The marker system already answers this for the two files several features
// share: a block in features_generated.go or routes_generated.go carries
// `// breeze:feature:<name>:start`, and upsertBlock rewrites only the region
// between one name's markers. What it did not answer is the same question for
// the standalone files each generator writes — models/user.go, ws/chat.go — and
// so nothing stopped one kind from writing over another's file. The check was
// only `os.Stat(path) == nil`, which reads "something is there" and cannot tell
// a stale model from a hand-written handler.
//
// That mattered as soon as --filename existed, because a mistyped override is
// the easy way to point one generator at another's output.
//
// The answer is not a second mechanism. Every generated stub already starts with
// the same marker the Go toolchain standardised —
//
//	// Code generated by `breeze generate model` — edit freely.
//
// which names its owner in the one place a file always has one. This reads that
// line back. The header is produced by generatedHeader below rather than written
// out per generator, so the string this parses is the string that was emitted.

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// generatedHeaderPrefix and generatedHeaderSuffix bracket the owner in the
// header line. They are the convention Go tooling recognises, so `gofmt -l`,
// `go vet` and this repository's own idiom check all treat the file as generated.
const (
	generatedHeaderPrefix = "// Code generated by `"
	generatedHeaderSuffix = "` — edit freely."
)

// generatedHeader is the first line of every generated stub.
//
// owner is the command that produced it, e.g. "breeze generate model". The
// wording after the marker is deliberate: these files are stubs to be filled in,
// unlike the marker-managed ones which say DO NOT EDIT because a hand edit there
// is refused on regeneration.
func generatedHeader(owner string) string {
	return generatedHeaderPrefix + owner + generatedHeaderSuffix + "\n"
}

// generateOwner is the owner string for a `breeze generate <kind>` command.
func generateOwner(kind string) string { return "breeze generate " + kind }

// fileOwner reports the command that generated the file at path.
//
// An empty owner means one of two things that are treated the same way: the file
// is not there, or it is there and was not written by a generator. Both leave
// the existing --force behaviour in charge, because in neither case is there
// another feature's work to protect.
//
// Only the first few lines are read. The header is the first line of everything
// this writes, and scanning a whole file to find a marker that is either at the
// top or absent would be waste.
func fileOwner(path string) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for i := 0; scanner.Scan() && i < 5; i++ {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, generatedHeaderPrefix) {
			continue
		}
		rest := strings.TrimPrefix(line, generatedHeaderPrefix)
		owner, _, found := strings.Cut(rest, "`")
		if found && owner != "" {
			return owner
		}
	}
	if err := scanner.Err(); err != nil {
		// handle/log as appropriate for your codebase
		return ""
	}
	return ""
}

// checkFileOwnership decides whether owner may write path.
//
// Three outcomes, and the middle one is the reason this exists:
//
//   - Nothing there, or something there that this same command wrote: the
//     existing rule applies unchanged — refuse without --force, so a stub the
//     user has since filled in is not silently discarded.
//   - A file another generator owns: refused outright. --force is not offered as
//     an escape here, and that is the point. --force means "replace what I
//     generated with what I would generate now"; it has never meant "delete
//     another feature's file", and reading it that way would make a mistyped
//     --filename destructive. The error names the other owner and the flag that
//     resolves the clash.
//   - A file with no generated header at all: hand-written, and treated like the
//     first case rather than the second. Refusing outright would make the
//     generators unable to write into a project that already has a file of that
//     name, which is a legitimate thing to want --force for.
func checkFileOwnership(path, owner string, force bool) error {
	if _, err := os.Stat(path); err != nil {
		return nil
	}

	if existing := fileOwner(path); existing != "" && existing != owner {
		return fmt.Errorf("%s is owned by `%s`, not by `%s` — refusing to overwrite another "+
			"feature's file\n       (--force does not apply here; pass --%s to write somewhere else, "+
			"or delete %s first if it is no longer wanted)",
			path, existing, owner, outputFilenameFlag, path)
	}

	if !force {
		return fmt.Errorf("%s already exists — pass --force to overwrite", path)
	}
	return nil
}
