package generator

import (
	"fmt"
	"strings"
)

const registryFileName = "routes_generated.go"

const registryHeader = `// Code generated by ` + "`breeze generate`" + `. DO NOT EDIT outside the
// marker blocks below â€” re-running generate for a resource replaces its
// block, and hand edits outside markers will be lost.

package main
`

// routeMarkerPrefix namespaces the route blocks inside routes_generated.go.
const routeMarkerPrefix = "breeze:route"

// registryTemplate is the routes_generated.go content written by `breeze
// new`, before anything has been generated. It deliberately omits the
// handlers import â€” Go rejects unused imports, and there's nothing to
// reference until the first `generate` call adds a block.
func registryTemplate() string {
	return registryHeader + `
import (
	"github.com/nelthaarion/breeze"
)

func RegisterGeneratedRoutes(router *breeze.Router) {
}
`
}

// ensureImports adds each import line to the import block if it isn't
// already present â€” e.g. the project's handlers package, or (for resource
// generation) the swagger and middleware packages. It's a no-op for any
// import a prior generate call already added.
//
// The anchor is the plain breeze import, which every generated file's
// template contains. Matching on the fully quoted path means
// "github.com/nelthaarion/breeze" does not match inside
// "github.com/nelthaarion/breeze/scalar", so subpackage imports are added
// rather than mistaken for the anchor.
func ensureImports(content string, importLines []string) string {
	breezeImport := `"github.com/nelthaarion/breeze"`
	for _, line := range importLines {
		if strings.Contains(content, line) {
			continue
		}
		content = strings.Replace(content, breezeImport, breezeImport+"\n\n\t"+line, 1)
	}
	return content
}

// upsertRouteBlock inserts or replaces the marker block for name inside the
// RegisterGeneratedRoutes function body of routes_generated.go, creating the
// file from the template if it doesn't exist yet. body is the raw Go source
// for the block's contents (without the marker comments). extraImports are
// additional import lines (e.g. swagger/middleware packages) the block needs
// beyond the handlers package, which is always ensured.
func upsertRouteBlock(modulePath, name, body string, extraImports ...string) error {
	imports := append([]string{fmt.Sprintf("%q", modulePath+"/handlers")}, extraImports...)
	return upsertBlock(blockRequest{
		FileName:  registryFileName,
		Initial:   registryTemplate(),
		Prefix:    routeMarkerPrefix,
		Name:      name,
		Body:      body,
		Imports:   imports,
		Placement: placeInLastBrace,
	})
}
